### ISSUE TITLE
Create how-to or tutorial example for BSM2

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1002]
Is there an example system using these translators? Would be cool if the user can run the example, can also help debugging.

But other than this and the one comment on `S_co2`, I don't have additional comments, thank you!

_Originally posted by @yalinli2 in https://github.com/watertap-org/watertap/pull/1000#pullrequestreview-1381465852_

**Comment by adam-a-a** [comment]
Note- I am merely creating this issue as a reminder based on @yalinli2 's comment on the translator PR (#1000 ). In other words, we shouldn't start this effort until we have the full BSM2 flowsheet (initial version) in place and stabilized. This would be important for the 2336 effort in having a broader impact--i.e., clear documentation with a working example on how to use our implementation of BSM2, while also showcasing the capabilities of BSM2 via EO modeling. 

@yalinli2 I am tagging you on this since UIUC is technically part of the model dev team, and I think in our last meeting, it was mentioned that you all have resources to start supporting more. Please let us know if we should add others, aside from you, from UIUC who could be tasked with model dev support on WaterTAP.

**Comment by yalinli2** [comment]
Thanks Adam for starting this thread. I'm departing soon so won't be officially contributing, but I'd like to stay in the loop and see what's happening.

@GaYeongKim and @RaiSaumitra will contribute to this. Ga-Yeong will be the lead (she's funded on the grant). Saumitra is actually funded on the METAB project, but he is working on developing BSM2 in QSDsan so he should be helpful.

I *think* at some point @joyxyz1994 should be able to help, but she's defending next month and will probably take some time off to celebrate, so let's not get her involved at this stage.

**Comment by GaYeongKim** [comment]
@adam-a-a Hi! This is Ga-Yeong Kim. I would be happy to contribute to this project! Could you please invite me (gayeong@illinois.edu) & @RaiSaumitra (sr60@illinois.edu) to WaterTAP Slack channel? Thanks!

**Comment by lbianchi-lbl** [comment]
This is related and/or part of #934.
