### ISSUE TITLE
Should CO2 be in ADM1 liquid phase too?

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1004]
@adam-a-a I'm wondering where this comment is from? Do you have another component for dissolved CO2? If `S_h2` and `S_ch4` can have liquid phase, I'd expect `S_co2` to have liquid phase as well as it's more dissoluble in the water

_Originally posted by @yalinli2 in https://github.com/watertap-org/watertap/pull/1000#discussion_r1164228942_

**Comment by adam-a-a** [comment]
@yalinli2 After further reflection, CO2 dissolved in the liquid phase would be accounted for in `S_IC`, inorganic carbon in liquid phase. Thus, `S_co2` is only explicitly considered in the gas phase in the ADM1 model. However, looking at the literature, `S_co2` in liquid phase could be represented as `S_IC - S_HCO3-`

If that adds up for everyone, we can close this issue.

**Comment by yalinli2** [comment]
OK, so you have reactions to account for the gas-liquid equilibrium of CO2? If that's the case then it should be OK, can you modify the comment to reflect this? Thank you!
https://github.com/watertap-org/watertap/blob/main/docs/technical_reference/unit_models/translators/translator_adm1_asm1.rst
https://github.com/watertap-org/watertap/blob/main/docs/technical_reference/unit_models/translators/translator_asm1_adm1.rst

**Comment by MarcusHolly** [comment]
Just for additional clarity, dissolved CO2 is represented by the constraint below in ADM1 (and Modified ADM1). I will update the documentation to make this more clear
![image](https://user-images.githubusercontent.com/96305519/233631163-f45a2b24-030e-4869-9c8b-c35008e5a6cb.png)
