### ISSUE TITLE
Best implementation for costing an AC to DC conversion for electrified processes

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1011]
### Description

Electrocoagulation, electrodialysis, and electrolysis mainly, but also other unit models, will require costing for rectification equipment and other associated costs. It is unclear on whether this should be done on a model-to-model basis or have a universal method when this utility is needed.

### Motivation

Several electrochemical processes will need this conversion and costing estimation, so the objective is to have a unified method to do this across models.

### Possible Implementation

- cost AC and DC as separate electricity flows, add method for efficiency of this conversion and other costs within the `watertap_costing_package` directly
- add rectification equipment unit model(?) block that converts current, feeds it to `cost_electricity_flow`, and may have it's own costing correlation as a unit model
- check IDAES and DISPATCHES for any existing implementation of this and standardize for WaterTAP

**Comment by hunterbarber** [comment]
This is up primarily as a place for discussion. I'm going to mention those involved on the electrochem team here just to gather their thoughts. @lbibl @avdudchenko @TimBartholomew @srikanthallu

**Comment by adam-a-a** [comment]
I missed today's discussion, but my initial thought would be to simply account for a general "power supplies" or "power electronics" cost category, which would be some value as $/kW (for CAPEX at least). As for electricity cost, I am guessing you would just cost DC electricity divided by electrical efficiency to get AC costs, so in that sense you could have AC and DC as separate "flows" if you wanted to be explicit about it.

EDIT: So I would start with a universal method, and depending on the unit model, you could swap the base value assumed for $/kW.

**Comment by hunterbarber** [comment]
> I missed today's discussion, but my initial thought would be to simply account for a general "power supplies" or "power electronics" cost category, which would be some value as $/kW (for CAPEX at least). As for electricity cost, I am guessing you would just cost DC electricity divided by electrical efficiency to get AC costs, so in that sense you could have AC and DC as separate "flows" if you wanted to be explicit about it.
> 
> 
> 
> EDIT: So I would start with a universal method, and depending on the unit model, you could swap the base value assumed for $/kW. 

From my memory, I think while a lot of the core electrified process units are relatively modular for CAPEX, the rectification equipment experiences more significant economy of scale. Whether to include this or not I would assume depends of what percentage of the total capital the rectification equipment is, because that motivates the need for more or less rigorous costing methods.

**Comment by adam-a-a** [comment]
On that note, I'll add that while our cost relationships from Watertap3 may have included economies of scale, our "detailed" unit models (e.g., RO) generally do not. So, as an initial implementation, I would start with the simpler (linear) cost assumption for rectifier (e.g., $1000/kW for umbrella "power electronics" or "power supplies" term) and later consider the addition of an alternative based on economies of scale that might also include further segregation of the cost components. Do we already have cost curve data for the rectifier by the way?

**Comment by hunterbarber** [comment]
Update: 
Waiting on electrochem subteam to gather data, then implementation will begin using a predetermined method discussed in this subteam.
