### ISSUE TITLE
Failure of macOS (EXPERIMENTAL) (3.8) checks on main

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1029]
### Description

Likely within the past week, a merged PR is causing failures in main w.r.t. the `macOS (EXPERIMENTAL) (3.8)` check. Until corrected, all new PR's and existing PR's merged with main are affected. The following failures are occuring:

```
FAILED watertap/property_models/tests/test_cryst_prop_pack.py::TestNaClPropertySolution_4::test_property_regression - ValueError: Cannot load a SolverResults object with bad status: error
FAILED watertap/unit_models/tests/test_electroNP_ZO.py::TestElectroNP::test_solution - assert 79571089844804.64 == 452890000000000.0 ± 4.5e+10
  comparison failed
  Obtained: 79571089844804.64
  Expected: 452890000000000.0 ± 4.5e+10
FAILED watertap/unit_models/tests/test_electroNP_ZO.py::TestElectroNP::test_costing - ValueError: Cannot load a SolverResults object with bad status: error
```

**Comment by adam-a-a** [comment]
Ben Knueven
  [1 day ago](https://nawi-watertap.slack.com/archives/C01DN1UL8KD/p1684325613156449?thread_ts=1684264504.682969&cid=C01DN1UL8KD)

> Ah the intel macOS binaries on conda-forge were updated a bit more than a day ago https://anaconda.org/conda-forge/ipopt/files.
> I had a look at the release notes for this version of ipopt and it changes a bit the handling of square problems that don’t achieve dual convergence: https://github.com/coin-or/Ipopt/releases/tag/releases/3.14.12.

**Comment by ksbeattie** [comment]
Testing for this is happening in: #1028 
https://github.com/coin-or/Ipopt/releases/tag/releases/3.14.12 and https://anaconda.org/conda-forge/ipopt/files  might explain it.

**Comment by lbianchi-lbl** [comment]
1. Latest passing CI run: https://github.com/watertap-org/watertap/actions/runs/4959649282/jobs/8874056530
2. Failing CI run: https://github.com/watertap-org/watertap/actions/runs/4995366002/jobs/8947143017

It looks like (1) has ipopt 3.14.11, while (2) has 3.14.12. I'll try to pin 3.14.11 in #1028 ans see if that makes any difference.
