### ISSUE TITLE
Update Node.js for GitHub Actions

### ISSUE THREAD

**Issue by wigging** [watertap-org/watertap#1044]
### Description

I see a bunch deprecation warnings for the GitHub Actions workflow (see image below). Looks like this repo's GitHub Actions workflow is using a deprecated version of Node.js.

<img width="991" alt="screenshot" src="https://github.com/watertap-org/watertap/assets/6828967/8fa6cadd-64c9-4e04-b5c2-7ff14d551519">

### Expected Behavior

Update Node.js to remove deprecation warnings for the GitHub Actions workflows.

### Steps to Reproduce

1. Select the GitHub Actions tab for this repo
2. Select a workflow
3. View warnings at bottom of the page

### Environment

GitHub Actions workflow page for this repository.

### Anything Else?

Nope.

**Comment by lbianchi-lbl** [comment]
Thanks for bringing this up. The way the warning is phrased might not make immediately clear how to proceed to resolve this. Node.js is one of the possible ways to _implement_ GitHub Actions (the framework) actions (the component/abstraction), so what this really means is that we should update the _tags_ of the specific actions mentioned there to a more recent version.

This will (eventually) get addressed as part of the CI workflow reorg I'm working on (see #1050). If someone wants to have this fixed before then, the things to do are:

- Make a note of which actions are using deprecated versions of Node.js from the warning messages
- For each affected actions, check the repository and note the most recent stable tag
  - Major tags only are fine for official actions (`actions/xyz`) and others such as `setup-miniconda` for readability
  - Third-party actions from individual developers should use the full commit hash for security
- Go through files in `.github/workflows` and update each use of the actions to the corresponding most recent tag
