### ISSUE TITLE
Seawater RO Energy Accounting

### ISSUE THREAD

**Issue by arao53** [watertap-org/watertap#1048]
### Description

In the seawater RO example flowsheet, the costing package doesn't add the specific energy consumption (SEC) attribute. This is a treatment train model so the SEC needs to be calculated using both the zero order and RO costing packages. There's an example of how this is done in the `dye_desalination_withRO` flowsheet.

### Motivation

SEC would be helpful for completeness and consistency with other flowsheets, as well as future modeling efforts that build on this model.

### Possible Implementation

See `dye_desalination_withRO` flowsheet.

**Comment by adam-a-a** [comment]
@arao53 -just stumbling upon this issue again and wanted to clarify the example you are referring to. My guess is that you mean this: https://github.com/watertap-org/watertap/blob/main/watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py

**Comment by arao53** [comment]
@avdudchenko clarified that we can actually get the total treatment train SEC using just the ZO costing package.
