### ISSUE TITLE
Clean up RO model and NaCl/seawater property models

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#105]
RUNNING TO DO: 

- [ ] remove RO parameter for pure water density since this is also included in property models 

- [ ] ensure all params/vars in property models have appropriate naming convention; seawater prop model should be more up-to-date than the NaCl model (ensure documentation reflects the updates as well)
- [x] Replace TDS references with NaCl in NaCl property documentation

- [ ] clean up #TODOs and comments that are no longer relevant 
- [x] remove set creation of `solvent_list` and `solute_list` and use `solvent_set` and `solute_set` #180

**Comment by TimBartholomew** [comment]
- [ ] Replace TDS references with NaCl in NaCl property documentation

**Comment by adam-a-a** [comment]
Aside from possibly removing water density from RO, this issue is no longer relevant.
