### ISSUE TITLE
Merging WaterTAP demo from NAWI Spring Meeting for June Release

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1061]
### Description

We'd like to have the code demo from the NAWI Spring Meeting show up in the June release. The demo included
1) a Jupyter notebook example for a pump + NF DSPMDE model (#1027)
2) a live demo of the GUI with (a) pump+NF and (b) pump+ NF with bypass stream

### Motivation

We should do this so that users can access what was presented at the Spring Meeting.

### Possible Implementation

- Implement the notebook in one PR #1027 
- include GUI export code and example for NF bypass in a separate PR since tests failing for Linux and not Windows (or vice-versa)
- include GUI export code and example for simple pump+NF flowsheet; could go in PR #1027 since it doesn't break tests

**Comment by adam-a-a** [comment]
In our last dev call, we decided to remove the problematic flowsheet example (NF+bypass) and move to a separate PR for resolution

**Comment by lbianchi-lbl** [comment]
Still some work needed to improve stability for the NF flowsheet, which is being tracked in #1072.
