### ISSUE TITLE
Update ZO model documentation wrt cost methods

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1064]
### Description

Changes in how the zero-model costing package was structured (#911), where costing methods for unit processes were moved from the package and into respective unit model classes, has caused a deviation from the automated documentation for ZO models, including models for IEDO FOA 2336 (i.e., not just migrated WT3 models that we tend to consider low priority).

### Expected Behavior

The automated documentation for ZO models was setup to extract constraint names and their descriptions and add them to a table in the rst file for a particular unit. For costing, a link was provided to documentation on the ZO cost package, which used to contain unit-level methods. Now, if the user goes to explore costing, they will not find unit-level costing methods anymore. Thus, the expected behavior is for users to go to documentation for a ZO unit and be directed to where some description of said costing methods is provided.

### Steps to Reproduce

1. Go to the technical reference for zero order unit models in WaterTAP's readthedocs: https://watertap.readthedocs.io/en/latest/technical_reference/unit_models/zero_order_unit_models/index.html

2. Pick any unit and try to learn more about how costing is conducted.

### Environment

NA

### Anything Else?

Any attempt to address this issue should use/modify the script for automatically generating ZO model documentation and should not be attempted manually (i.e., not by editing ZO unit model rst files directly).

**Comment by lbianchi-lbl** [comment]
This should be done sooner rather than later, but being documentation, doesn't have to make the release necessarily.
