### ISSUE TITLE
add MCAS usage example

### ISSUE THREAD

**Issue by rkingsbury** [watertap-org/watertap#1071]
### Description

Thanks for the excellent work on WaterTAP. The multicomponent `MCASParameterBlock` property model model looks particularly compelling and powerful. I am requesting that you add a How-To along the lines of [How to Use a Property Model](https://watertap.readthedocs.io/en/stable/how_to_guides/how_to_use_a_property_model.html) for this model. Thanks!

### Motivation

The MCAS property model appears to be the only one in WaterTAP that can report activity coefficients of species, making it the only feasible choice for certain types of analysis (e.g., Ion Exchange). However, the example code shown in [How to Use a Property Model](https://watertap.readthedocs.io/en/stable/how_to_guides/how_to_use_a_property_model.html) is apparently not quite adequate for using this particular property model, because if I replace `NaCl_prop_pack` and `NaClParameterBlock` with `multicomp_aq_sol_prop_pack` and `MCASParameterBlock`, respectively, the example fails with an error (details in "Additional Context" section). As such, the MCAS model is effectively inaccessible to users until an example can be added to the documentation.

### Additional Context

Copying the example code from [How to Use a Property Model](https://watertap.readthedocs.io/en/stable/how_to_guides/how_to_use_a_property_model.html) and then replacing `NaCl_prop_pack` and `NaClParameterBlock` with `multicomp_aq_sol_prop_pack` and `MCASParameterBlock`, respectively, fails with

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/var/folders/pz/fdnb8v9529zftp5v9d8s9gb40000gn/T/ipykernel_72009/1390382182.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/pz/fdnb8v9529zftp5v9d8s9gb40000gn/T/ipykernel_72009/1390382182.py) in ()
     13 m = ConcreteModel()
     14 m.fs = FlowsheetBlock(dynamic=False)
---> 15 m.fs.properties = MCASParameterBlock()
     16 
     17 # Build the state block and specify a time (0 = steady state).

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py) in __setattr__(self, name, val)
    578                 # Pyomo components are added with the add_component method.
    579                 #
--> 580                 self.add_component(name, val)
    581             else:
    582                 #

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py) in add_component(self, name, val)
   1183                 )
   1184             try:
-> 1185                 val.construct(data)
   1186             except:
   1187                 err = sys.exc_info()[1]

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py) in construct(self, data)
   2189                             obj.construct(data.get(name, None))
   2190                 # Trigger the (normal) initialization of the block
-> 2191                 self._getitem_when_not_present(_idx)
   2192         finally:
   2193             # We must allow that id(self) may no longer be in

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/block.py) in _getitem_when_not_present(self, idx)
   2109 
   2110         try:
-> 2111             obj = self._rule(_block, idx)
   2112             # If the user returns a block, transfer over everything
   2113             # they defined into the empty one we created.  We do

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/initializer.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/pyomo/core/base/initializer.py) in __call__(self, parent, idx)
    311             return self._fcn(parent, *idx)
    312         else:
--> 313             return self._fcn(parent, idx)
    314 
    315 

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/idaes/core/base/process_block.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/idaes/core/base/process_block.py) in _rule_default(b, *args)
     37     """
     38     try:
---> 39         b.build()
     40     except Exception:
     41         logging.getLogger(__name__).exception("Failure in build: {}".format(b))

[~/miniconda3/envs/watertap/lib/python3.8/site-packages/watertap/property_models/multicomp_aq_sol_prop_pack.py](https://file+.vscode-resource.vscode-cdn.net/Users/ryan/Library/CloudStorage/OneDrive-PrincetonUniversity/1_Research/4_execution/WaterTAP/~/miniconda3/envs/watertap/lib/python3.8/site-packages/watertap/property_models/multicomp_aq_sol_prop_pack.py) in build(self)
    314 
    315         # Group components into different sets
--> 316         for j in self.config.solute_list:
    317             if j == "H2O":
    318                 raise ConfigurationError(

TypeError: 'NoneType' object is not iterable
```

I gather from the error (and some code-diving) that I need to somehow specify either the species property database to draw from (perhaps the EDB [component.json](https://github.com/watertap-org/watertap/blob/main/watertap/edb/data/component.json)? ) or the composition of the solution when I instantiate the property block, but I can't figure out how to do so.

Interestingly, if I just directly instantiate the block (outside of a flowsheet), I don't get the error. I can also retrieve `m.fs.properties` and get back an instance of the MCAS property block

```
>>> m.fs.properties
<idaes.core.base.process_block._ScalarMCASParameterBlock at 0x7fbe39ffccc0>
```

```
>>> MCASParameterBlock()
<idaes.core.base.process_block._ScalarMCASParameterBlock at 0x7fbe39f9a130>
```

Note that I am using the `pip` version of water tap, v0.8.0, though I may try the git version soon.

**Comment by adam-a-a** [comment]
@rkingsbury Thank you for your feedback, and happy to have your eyes on this. I agree that we should add a how-to on this issue. To give you a little context, this property model was originally developed for use with the Donnan Steric Pore Model w/Dielectric Exclusion (DSPM-DE). In the interim, you can find some examples of MCAS' usage in test files as well as flowsheet examples. Feel free to check out some of these below until we get a how-to up and merged:

- Test file for MCAS: https://github.com/watertap-org/watertap/blob/main/watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
- Test file for NF DSPM-DE unit: https://github.com/watertap-org/watertap/blob/main/watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
- Flowsheet example for electrodialysis: https://github.com/watertap-org/watertap/blob/main/watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc.py#L117-L124

I'll note that ion exchange and GAC unit models also make use of MCAS. I should also mention that the user has to provide data for the solutes that are specified (i.e., MCAS doesn't act as a database). However, we are considering usage of external software (e.g., OLI) with MCAS in the future.

**Comment by adam-a-a** [comment]
TO DO:

- [x] Add how-to for MCAS
- [x] Provide more useful exception when the user doesn't provide a `solute_list`
- [x] Probe for other potential errors when expected args are not provided to MCAS

**Comment by rkingsbury** [comment]
Thank you @adam-a-a ! The test files will are helpful. So, is the `component.json` data file in `edb` unrelated to MCAS? (In other words, not intended to be imported or otherwise used with it?)

**Comment by adam-a-a** [comment]
No problem, @rkingsbury! The `edb` was originally intended for use with the [IDAES modular property framework](https://idaes-pse.readthedocs.io/en/latest/explanations/components/property_package/general/index.html#modular-property-package-framework), from what I recall. Here is an example for using the modular property framework in WaterTAP: https://github.com/watertap-org/watertap/blob/main/watertap/examples/chemistry/tests/test_chlorination.py#L134-L697
You can find more examples in the chemistry test files within that same folder.

More background: I started MCAS because I needed something that would streamline development of the DPSM-DE model, and at the time, it seemed more straightforward to implement my own property model rather than adhere to some of the requirements of the modular property framework. MCAS subsequently became useful for other units and was built upon from there. 

With that said, we hadn't thought about using the `edb` with MCAS, but maybe this is something we should look into. @dangunter led development of the `edb`. @lbibl also contributed to MCAS and is the main developer of the electrodialysis unit models that we currently have. @hunterbarber has also contributed to MCAS.

**Comment by rkingsbury** [comment]
Thanks for the great context @adam-a-a ; having worked through the linked examples this is all making a lot more sense. I see now that MCAS is pretty straightforward: given some basic input data for each solute (e.g., charge, molecular weight, diffusivity), it can calculate a series of phase properties, depending on how the model is configured. If I'm understanding correctly, MCAS does not model reactions or equilibrium; just the relationships between solute and phase properties.

This is very similar in spirit to my package [pyEQL](https://pyeql.readthedocs.io/en/latest/tutorial.html), which contains a built-in ion database and is designed to handle complex and highly concentrated solutions. I'm in the process of [modernizing](https://github.com/rkingsbury/pyEQL/pull/22) this package (originally written in 2013-4 when I didn't know very much about software engineering!) and looking at how to tie it into other aqueous chemistry platforms including WaterTAP.

Looking forward to further discussion.
