### ISSUE TITLE
Cost reporting options for results of unit models and flowsheets

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1083]
### Description

There currently is not support for a printable option of `UnitModelCostingBlock` or `WaterTAPCostingBlock` classes. Something analogous to `unit_model.report()` would allow for a clearer consolidated input of relevant costing results. Currently, these may only be viewing through `m.fs.costing.display()` or accessing values individually.

### Motivation

For a single user, this allows for a better visual option for results. 
For more in-depth analyses, a solution may also create a more accessible cost breakdown.

### Possible Implementation

Likely will require a method (of low to moderate effort to get everything to work as intended) within the `watertap_costing_package`

**Comment by kurbansitterley** [comment]
I had something like this in WT3 that automatically printed high level costing metrics for the whole system and each unit automatically when the model was solved. It was incredibly useful and in some cases made troubleshooting strange results much easier. Included:

- Capex
- Annual O&M
- Annual fixed O&M
- Annual chem cost
- Annual electricity cost
- LCOW
- Qin 
- Qout

Not saying we take this exact approach, but I think its a great idea and I support the endeavor.

**Comment by hunterbarber** [comment]
I'll assign myself but it is lower priority on my TODOs

**Comment by adam-a-a** [comment]
This is a great suggestion and would be willing to help with this one when time permits. Adding to what @kurbansitterley said, I always liked looking at **LCOW breakdowns** to help me make sense of things and debug model issues when needed too.

**Comment by hunterbarber** [comment]
> This is a great suggestion and would be willing to help with this one when time permits. Adding to what @kurbansitterley said, I always liked looking at **LCOW breakdowns** to help me make sense of things and debug model issues when needed too.

Very late reply, but I'm looking back into this right now. So for the new `MultiUnitModelCostingBlockData` I needed to calculate LCOW by unit model option specifically because the breakdown was more relevant. I also like knowing the LCOW contribution by unit, but it is definitely not readily available as is.

**Comment by hunterbarber** [comment]
I think the unit model costing is as simple as a `_get_performance_contents` on the unit model costing build, and I'm working on the flowsheet portion now. It would overwrite the empty report call from [idaes/core/base/costing_base.py#L511](https://github.com/IDAES/idaes-pse/blob/main/idaes/core/base/costing_base.py#L511).

**Comment by hunterbarber** [comment]
Closing due to very low priority, can reopen time permitting.
