### ISSUE TITLE
Possible deadlock/timeout issues in MPI CI jobs

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#1227]
![image](https://github.com/watertap-org/watertap/assets/48035537/68ce6f24-1e0d-4c0f-8601-0ea95b67485c)

**Comment by bknueven** [comment]
Maybe #1222 has fixed this?

**Comment by ksbeattie** [comment]
When's the last time we saw this?

**Comment by ksbeattie** [comment]
Closing this issue as we haven't seen it happen recently.
