### ISSUE TITLE
Removing unused, unmaintained, and/or deprecated code

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#1230]
### "Retirement"

- Delete the code from the WaterTAP repository
- Create a dedicated repository for the code under watertap-org

### "Graveyard"

- Delete the code from the WaterTAP repository
- Add an entry to a common document, with pointers to the latest commit/release where the removed code was available

## Possible applications

- [ ] `watertap/examples/chemistry/tests`
  - Strategy: "graveyard"
  - Will likely done as part of ~~#1224~~ actually #1229
- [ ] ElectrolyteDB
  - Strategy: "retirement

**Comment by ksbeattie** [comment]
This is being done in #1248
