### ISSUE TITLE
Stream table reporting for the UI

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1231]
### Description

Opposed to specifying the stream variables to output to the UI "output" tab in the existing variable block representation, has there been discussion regarding a stream reporting option within that tab?

### Motivation

Conciseness of reporting within UI

### Possible Implementation

I imagine the backend from the watertap dev flowsheet side would be instead of specifying the variables one by one, you would specify the state blocks or arcs to include and state variables with units to display, then the backend UI would perform the matrix to pull those variables for all specified streams in the desired units.

**Comment by hunterbarber** [comment]
@MichaelPesce @dangunter Bringing this up because I didn't see any history of conversation around it in the open or closed issues, have this been discussed and either trashed, backlogged, or prioritized in the past?

**Comment by dangunter** [comment]
We have a stream table that's auto-generated in the IDAES flowsheet visualizer, we could probably just re-use that.. user wouldn't need to do anything to generate it. Have you used that one, would it work for you?

**Comment by hunterbarber** [comment]
I think porting available stuff over makes a lot of sense and should work. I personally haven't used it so I'm not familiar. This isn't a necessity for sure, but I do think it is a very nice to have for concise reporting.

**Comment by hunterbarber** [comment]
Closing as duplicated in UI [#100](https://github.com/watertap-org/watertap/issues/1623) and [#97](https://github.com/watertap-org/watertap-ui/issues/97)
