### ISSUE TITLE
MPI-Related Bug

### ISSUE THREAD

**Issue by MarcusHolly** [watertap-org/watertap#1233]
### Description

When working on this PR (https://github.com/watertap-org/watertap/pull/1177), I ran into this error `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process` (see screenshot below). I was able to resolve the failure by changing the spacer porosity in the associated flowsheet, but the connection between that value and this failure isn't obvious to me, so I'm assuming it's a bug.
![image](https://github.com/watertap-org/watertap/assets/96305519/bdc1542e-2969-4f82-9482-b1a798723451)

### Expected Behavior

PermissionErrors should not be dependent on/affected by the value of variables in flowsheets.

### Steps to Reproduce

Run this commit on Windows: https://github.com/watertap-org/watertap/pull/1177/commits/67398436c4c655efb7e747b19d6f9848622384db

### Environment

- OS: Windows
- Python: 3.8
- WaterTAP: 0.11.dev0

**Comment by bknueven** [comment]
The loop tool uses the RO w/ ERD flowsheet in its tests.

You probably need to update the value in the failing test above -- I am guessing it didn't clean up after itself when it failed.

**Comment by k1nshuk** [comment]
I need to confirm this behavior but, on first glance, it seems that in [test_sweep_backup](https://github.com/watertap-org/watertap/blob/67398436c4c655efb7e747b19d6f9848622384db/watertap/tools/analysis_tools/loop_tool/tests/test_loop_tool.py#L257C5-L257C22) both MPI ranks are trying to read the H5 files, which usually spells trouble in my experience.

**Comment by k1nshuk** [comment]
Please disregard my previous comment. I have deleted it.

**Comment by MarcusHolly** [comment]
@bknueven Thanks - you are right. Those two failures are coupled together... I had assumed they were independent errors, but after fully resolving the first, the PermissionError resolved itself locally. I think I'll close this issue when I confirm that there are no lingering failures in the PR.

**Comment by bknueven** [comment]
@MarcusHolly please leave it open -- for now. I want to see if that test is not cleaning up after itself.

**Comment by k1nshuk** [comment]
@MarcusHolly can you repeat the experiment with the following branch on my fork and see if the coupled error goes away?
https://github.com/k1nshuk/watertap/tree/fortify_loop_tool_test

**Comment by bknueven** [comment]
Closed by #1236
