### ISSUE TITLE
Input based `build_options` in UI validated by `class`

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1239]
### Description

The UI supports build options that are validated from selecting a value from a drop down list. This is good where the config options are only a small fixed set. For the GAC model though, the flowsheet is generalized for any water and solute system. The name and properties (molecular weight, etc.) of the "solute" should be constructed during the build for the most standard solve and ability to integrate the specific name into the input/output results. I think the possible implementation provided is one such idea to make this possible.

### Motivation

Advancing robustness and options of UI.

### Possible Implementation

So I started testing the implementation of a `var_type_allowed` in a addition to the existing `values_allowed` option. In `var_type_allowed` the `class` could be specified ('str' or 'float') that is validated before the `values_allowed`. Then either or both options are to be specified, and raise an error if neither is specified in the `build_options`. However this also requires the drop down box to change to a input box when `values_allowed` is empty (input your own string) in the UI which was out of my expertise.

**Comment by hunterbarber** [comment]
Note, is unnecessary with other changes proposed in #1238. It may still be a nice future feature so I will change to low priority but not close this for now.

**Comment by hunterbarber** [comment]
@dangunter @MichaelPesce Is this closed as of #1270, or still pending and recorded in UI [#98](https://github.com/watertap-org/watertap-ui/issues/98) that this is duplicate? Just trying to clean up and properly link PRs to issues I'm assigned/authored.

**Comment by MichaelPesce** [comment]
@hunterbarber yup this is closed in #1270 (and UI PR [#104](https://github.com/watertap-org/watertap-ui/pull/104)) as well as recorded in UI [#98](https://github.com/watertap-org/watertap-ui/issues/98).

**Comment by hunterbarber** [comment]
Closed in [#1270](https://github.com/watertap-org/watertap/pull/1270) (and UI PR [#104](https://github.com/watertap-org/watertap-ui/pull/104))
