### ISSUE TITLE
LCOW and SEC breakdown functionality and display in UI

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1256]
### Description

Streamlining the breakdown of LCOW calculations in the costing package and quickly displaying them (e.g., stacked bar charts) in the UI.

Similarly we should be able to do the same for SEC calculations.

### Motivation

would be very useful for interpreting results as well as identifying modeling errors.

### Possible Implementation
Implementation should happen in (1) costing package base and (2) the UI.

compute an annualized capital cost per unit and be able to specify level of aggregation desired. For example, I may have a multi-stage system with a pump or two in each stage, but I may or may not want to look at the cost breakdown for each pump OR just aggregate pumps across all stages and show one segment of the stacked bar chart as "pump costs". 

Similarly we should be able to do the same for SEC breakdown---i.e., specify level of desired aggregation. 

### Additional Context

Presenting LCOW and SEC breakdowns is common practice and WaterTAP can be used to facilitate generation of said results. 

Otherwise, we have to write code manually to do this, which isn't diffiicult but can be time consuming.

**Comment by hunterbarber** [comment]
With #1231, should be have a running document of UI brainstorming and feature requests? Either as an internal doc or running issue. #1231 is in the same sprit of less manual code input on the backend and more intuitive visualization tools in the UI.

**Comment by adam-a-a** [comment]
Sounds good- can you create a "master" issue that links to this and #1231 to start?

**Comment by dangunter** [comment]
From discussions today this can be thought of more generically as presenting stacked bar charts in the UI. The interface from the backend would be basically returning table with a column for each bar and rows for each value in the stack. This would be useful for costing or any other value that needs to be displayed this way.

**Comment by hunterbarber** [comment]
Closing because issue is duplicated in [#101](https://github.com/watertap-org/watertap-ui/issues/101) of UI repo
