### ISSUE TITLE
More detailed pressure exchanger

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#1262]
### Description

Allow users to model a pressure exchanger that accounts for leakage, mixing, and the pressure differential within a pressure exchanger.

### Motivation

Including mixing and leakage will make the model more realistic. Additionally, the primary manufacturer of pressure exchangers (Energy Recovery) provides mixing and leakage rates on their specification sheets.

### Possible Implementation

This implementation should be relatively straight forward.

1. Enable mass transfer for each control volume: has_mass_transfer = True
   - Adding a constraint to connect the mass transfer terms: mass_transfer_term_HPS = - mass_transfer_term_LPS
3. Incorporate leakage by:
   - Ensuring the equal volumetric flowrate constraint is only for the inlets: Q_LPS_in = Q_HPS_in
   - Adding a new fixed variable for the volumetric leakage called leakage_vol (default value = 0.01)
   - Adding a constraint to account for the leakage: Q_HPS_in * (1 - leakage_vol) = Q_HPS_out
4. Incorporate mixing by:
   - Adding a new fixed variable for the volumetric mixing called mixing_vol (default value = 0.035)
   - Adding a constraint to account for the mixing: C_LPS_out = C_LPS_in * (1 - mixing_vol) + C_HPS_in * mixing_vol
5. Incorporate pressure differential by:
   - Ensuring the efficiency_pressure_exchanger is unfixed. Note: that we can keep it and the pressure transfer constraint because now the unfixed variable will just be calculated.
   - Adding a new fixed variable for the pressure differential called high_pressure_difference (default value = 0.8 bar)
   - Adding a constraint to account for the pressure differential: P_LPS_out + high_pressure_difference = P_HPS_in
   - Note: we can keep our previous assumption that P_HPS_out = P_LPS_in

Since we would like users to have access to our previous simpler model and this newer more detailed one, we should pair these changes with a configuration argument(s). I can see two options:
1. A single configuration argument for switching between the two models. The configuration argument could be level_of_detail, with the options being simple and detailed. (Although I'm not sure about those names, both are relatively simple assumed performance models)
2. Multiple configuration arguments for the modeled phenomena/relationships.
   - A configuration argument for leakage - has_leakage and the options can be True or False
   - A configuration argument for mixing - has_mixing and the options can be True or False
   - A configuration argument for the pressure exchange calculation - pressure_exchange_calculation and the options can be "efficiency" or "high pressure difference"
   - If we go with this option, we need to be sure the model is still well formulated for when has_leakage is True but has_mixing is False or vice versa.

**Comment by TimBartholomew** [comment]
@luohezhiming @avdudchenko @adam-a-a, I added all of you because I'm not sure who should do it. This should be pretty quick and I know any of you can do it, I'm leaning towards Chenyu, but if Alex or Adam want to do it that's totally fine.

**Comment by adam-a-a** [comment]
@TimBartholomew I agree- I think it would make sense for @luohezhiming to focus on implementing the code, I can support and provide guidance to @luohezhiming on implementation, and we can get feedback from @avdudchenko and @TimBartholomew as needed. Sound good to all?

**Comment by adam-a-a** [comment]
That said, I don't expect that @luohezhiming will need too much support or feedback from us given the clear guidelines on what needs to be done.

**Comment by adam-a-a** [comment]
As for configuration arguments, would go with the second option as it is (1) more consistent with how we setup config options across other WaterTAP models and (2) would allow the user to observe results when toggling any one of those options on or off (as opposed to having all options on or off at once).

**Comment by luohezhiming** [comment]
Sounds good to me, Tim has given a clear guidance, I will try to implement it based on that with separate configurations for each options. If not work, then I'll try pack these as one config.
