### ISSUE TITLE
MCAS `ElectricalMobilityCalculation.EinsteinRelation` does not allow for `DiffusivityCalculation.HaydukLaudie`

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#1305]
### Description

`ElectricalMobilityCalculation.EinsteinRelation` does not allow for `DiffusivityCalculation.HaydukLaudie` due to the check in line 1526 of MCAS

### Anything Else?

Need to change the check in line 1526 from looking for `self.params.config.diffusivity_data.keys()` for `DiffusivityCalculation`s that are functions of other parameters and do not require `self.params.config.diffusivity_data.keys()`. This is an easy fix to change the check through a couple different implementations, but not sure of which is the most future-proof, and not sure if this needs tested somewhere.

**Comment by lbibl** [comment]
Electrochemical mobility is only allowed on ions while HaydukLaudie is only for neutral species.  Why is there an issue ?

**Comment by hunterbarber** [comment]
> Electrochemical mobility is only allowed on ions while HaydukLaudie is only for neutral species. Why is there an issue ?

You're right. I double checked the doc strings and they do specify that Hayduk Laudie is for 'nonelectrolyte' and electrochemical mobility is for 'ions' so I think its clear.
