### ISSUE TITLE
Documentation Failures

### ISSUE THREAD

**Issue by MarcusHolly** [watertap-org/watertap#1307]
### Description

Documentation failures related to "how_to_guides\how_to_use_MCAS_property_model.rst" and "how_to_guides/how_to_use_a_property_model" are appearing in unrelated PRs (see #1294 or #1301 or #1306). So I imagine something problematic was merged into main recently.

### Environment

- OS:
- Python:
- WaterTAP:

**Comment by lbianchi-lbl** [comment]
- It looks like the failures are due to changes in the expected output in two of the doctests
- One non-code-related change we're aware of is Pyomo 6.7.1 being released
- I've opened #1308 to look into this

**Comment by lbianchi-lbl** [comment]
This is the diff between the expected ([expected.txt](https://github.com/watertap-org/watertap/files/14391338/expected.txt), left) and actual ([got.txt](https://github.com/watertap-org/watertap/files/14391337/got.txt), right) for one of the failing tests, corresponding to https://watertap.readthedocs.io/en/stable/how_to_guides/how_to_use_a_property_model.html:

![image](https://github.com/watertap-org/watertap/assets/48035537/9a9845b3-7d4c-4eeb-8191-9eb318dd3609)

**Comment by lbianchi-lbl** [comment]
@andrewlee94 do you have any idea what could have caused this change? The doctests pass (i.e. the output matches the expected one on the left in the screenshot above) with Pyomo 6.7.0 (compare 0aed4d1 and 6507237).

**Comment by andrewlee94** [comment]
@lbianchi-lbl I think I do know - it is a Pyomo change to how they handle implicit Sets. In short, in this case it looks like the component was indexed by a Set union which was declared implicitly (e.g. `m.v = Var(m.set1, m.set2, ...)`). Pyomo has changed to be much more explicit about how they handle implicit sets which has changed the name these sets.

Short answer is I think that the variables should be indexed by the existing `phase_component_set`.
