### ISSUE TITLE
Spiral-wound module type issues with OARO

### ISSUE THREAD

**Issue by zacharybinger** [watertap-org/watertap#1380]
### Description

So there is a issue with applying the spiral-wound module type to the OARO unit model or any future osmotically-driven membrane process that operates with two fluids on each side of the membrane. To operate with two streams on a spiral-wound module, a baffle needs to be added to the "permeate side" of the envelope. I attached a figure to visualize this. I will try coming up with a simple solution to this issue, but wanted to create an issue to highlight the possibility of removing the spiral-wound module_type from OARO.
![1-s2 0-S0011916419323653-gr5_lrg](https://github.com/watertap-org/watertap/assets/23547346/d8a73f31-1a7d-4023-9c19-7fd2fbc20f0f)

### Expected Behavior

- Error in permeate recovery prediction

### Environment

- OS:
- Python:
- WaterTAP:

**Comment by adam-a-a** [comment]
One approach is to undo the changes made that affected OARO in #1272 (we want to keep the changes that affected RO though). FYI @MarcusHolly @ElmiraShamlou @luohezhiming
