### ISSUE TITLE
TypeError: metaclass conflict failures with Pyomo 6.7.2, IDAES 2.4.0

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#1382]
This happens when using Pyomo 6.7.2 with IDAES 2.4.0

![image](https://github.com/watertap-org/watertap/assets/48035537/64dce553-2212-4873-a66e-4bfa37ffb84b)

**Comment by ksbeattie** [comment]
I think this is being worked on here: https://github.com/IDAES/idaes-pse/pull/1404

**Comment by lbianchi-lbl** [comment]
> I think this is being worked on here: [IDAES/idaes-pse#1404](https://github.com/IDAES/idaes-pse/pull/1404)

To provide more details, my understanding of what's happening (which might be at least partially incorrect) is the following:

- This error in the happens when using the "old" underscore-prefixed Pyomo class names with Pyomo 6.7.2 (because of the deprecation mechanism) together with IDAES's `ProcessBlock`
- The cause of this is the presence of multiple non-related metaclasses appearing in the class hierarchy, namely:
  - (A) Metaclass used by the Pyomo deprecation infrastructure (i.e. only classes with deprecated names will have this metaclass)
  - (B) Metaclass used by the `ProcessBlock` implementation in IDAES
- This issue has been addressed by IDAES/idaes-pse#1402, which removes the conflict by updating to the new (current) non-underscore-prefixed class names throughout the IDAES codebase (i.e. removing (A))
  - Therefore, using Pyomo 6.7.2 with a version of `idaes-pse` that includes #1402 (such as the current `IDAES/idaes-pse:main`) **will not be affected** by this error
  - Conversely, using Pyomo 6.7.2 with a version of `idaes-pse` that does not include #1402 (such as the most recent stable release 2.4.0) **will be affected** by this error
- IDAES/idaes-pse#1404 is a different (and, after #1402, complementary/redundant) approach to resolve the issue, as it would remove the use of `metaclass` in `ProcessBlock` (i.e. removing (B))

**Comment by andrewlee94** [comment]
Also, Pyomo has added a bug fix to address this failure so it should work now even if the class names are not updated (you will see a lot of deprecation warnings however).

**Comment by lbianchi-lbl** [comment]
Based on what I can see, the Pyomo fix might not be enough when IDAES (before IDAES/idaes-pse#1402) is also involved. e.g. the following reproduces the error above:

```sh
conda create --yes --name test-watertap-1382 python=3.11 && conda activate test-watertap-1382
pip install watertap==0.12.0 pytest
pip list  # should display idaes-pse==2.4.0, pyomo==6.7.2
pytest --pyargs watertap
```

**Comment by andrewlee94** [comment]
Interesting - I had hoped that either one would be sufficient alone, but maybe not. However, given that both are now merged and will be in the next releases, is there any remaining problems (at least on the IDAES/Pyomo end)? WaterTAP should check to make sure they are not using any of the renamed components (this mostly shows up in test files).
