### ISSUE TITLE
Need how-to guide that illustrates utilization of EDB in model development

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#140]
Quoting the guide on [how to setup simple chemistry](https://watertap.readthedocs.io/en/latest/how_to_guides/how_to_setup_simple_chemistry.html):
> Much of the difficulties and complications with setting up a proper thermo-properties configuration dictionary can be handled by the Electrolyte Database system in ProteusLib (Documentation pending)

A how-to guide should be created not only to elaborate on this quote, but also to show the reader how to implement the EDB for developing models.

**Comment by dangunter** [comment]
@adam-a-a the link above is broken now

**Comment by adam-a-a** [comment]
@dangunter I updated the link (changed "proteuslib" to "watertap" in the url)
