### ISSUE TITLE
Add Technical References to documentation

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1408]
Currently, we are missing technical references from some fundamental units such as the Pump and "pressure changer" (i.e., pelton-turbine/reversible pump type). These should be included in version 1.0. We can reference IDAES' form of these unit models where appropriate and add any detail on what additions/changes are applied in the WaterTAP version of said units. 

Running list:

- [x] Pump @luohezhiming #1452 
- [x] EnergyRecoveryDevice  @luohezhiming #1452

**Comment by kurbansitterley** [comment]
In making #1425 I noticed we are also missing docs for the ZO prop package and WaterTAP database. Important? Should we add to this issue? @adam-a-a

**Comment by adam-a-a** [comment]
We should have documentation at the following link, but we can think about moving to a higher level to be more transparent: https://watertap.readthedocs.io/en/stable/technical_reference/core/index.html
