### ISSUE TITLE
Background on why we need/want the EDB

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#141]
A brief doc on why we want the EDB and how it simplifies the setup of chemistry configurations for model development would be beneficial. 

At the surface-level, it may seem obvious that storing data in a database for simple queries and loading would be more efficient than manually entering thermo config dictionaries (for example), but it would be nice if we could really spell out the purpose and benefits of having the EDB and the role that it plays specifically in Proteuslib. 

From a more holistic perspective, perhaps we should come up with a schema (if a currently relevant one doesn't already exist) that illustrates the main components of a complete Proteuslib workflow and where the EDB fits in.

**Comment by aladshaw3** [comment]
Would this be a separate document from the one wanted in #140 ?

**Comment by adam-a-a** [comment]
We're attempting to have separate docs for background/explanation and the how-to, with the hope that this approach will make our documentation better in the long run. 

Since we are trying to follow the Diataxis framework, we currently have 4 main categories in [read the docs](https://proteuslib.readthedocs.io/en/latest/): 

- [Tutorials](https://diataxis.fr/tutorials/), 
- [How-Tos](https://diataxis.fr/how-to-guides/), 
- [Background](https://diataxis.fr/explanation/)
- [Technical Reference](https://diataxis.fr/reference/). 

So #140 would be like a recipe for how to make use of the EDB when creating models (via code examples), while this background/explanation doc would give some high-level discussion on _why_ we created the EDB and _how_ it can benefit model development.
