### ISSUE TITLE
Seemingly random MacOS failure in test_cstr

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1473]
I have seen the following glitch show up in MacOS checks which I can resolve by just rerunning the check. Just seeing this for the second time on the same file (test_cstr) so reporting it in case it pops up again.

![image](https://github.com/user-attachments/assets/273091b4-9415-4dc0-8e93-55bea749da8d)

**Comment by lbianchi-lbl** [comment]
Zooming out a bit, we should consider dropping support for (i.e. stop testing in CI) the IDAES-less macOS environment. It's a non-negligible maintenance burden and we might decide it's not worth it.

See also: #1306

**Comment by adam-a-a** [comment]
Noticed this failure on #1471

**Comment by lbianchi-lbl** [comment]
> Zooming out a bit, we should consider dropping support for (i.e. stop testing in CI) the IDAES-less macOS environment. It's a non-negligible maintenance burden and we might decide it's not worth it.
> 
> See also: #1306

This (i.e. replacing our "bootleg" macOS CI environment with Apple Silicon GHA runners using IDAES solvers) is being done in #1483.

**Comment by lbianchi-lbl** [comment]
- As @adam-a-a points out, this could be an issue with a change in IDAES between version 2.5.0 and the upcoming 2.6.0
- The motivation for this hypothesis is that the changes in #1471 are not related to the failing check, but #1471 does update the `idaes-pse` requirement to be `IDAES/idaes-pse:main`
- We expect to be able to verify this by creating a PR that contains only the change to the `idaes-pse` requirement, which is planned as soon as `idaes-pse` 2.6.0rc0 is available

**Comment by lbianchi-lbl** [comment]
The macOS CI check is indeed failing in the same way in #1486, which would confirm @adam-a-a's hypothesis/observation that the failure is possibly related to a change in IDAES between versions 2.5.0 and 2.6.0rc0: https://github.com/watertap-org/watertap/actions/runs/10747258986/job/29809470692

![image](https://github.com/user-attachments/assets/eb82a38d-05ea-4df9-8728-d7d6f6ea4a18)

**Comment by adam-a-a** [comment]
@lbianchi-lbl this same test exists on IDAES for the same unit. The only difference is in the WaterTAP version of this unit, we add a variable and simple constraint. That is, we add hydraulic retention time as a variable and the associated constraint for it, relating retention time to reactor volume and inlet flowrate.

I don't know if this cstr test may have had a similar macOS test failure on the IDAES repo.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl this same test exists on IDAES for the same unit. The only difference is in the WaterTAP version of this unit, we add a variable and simple constraint. That is, we add hydraulic retention time as a variable and the associated constraint for it, relating retention time to reactor volume and inlet flowrate.
> 
> I don't know if this cstr test may have had a similar macOS test failure on the IDAES repo.

Thanks for the extra info @adam-a-a. On the IDAES side, I don't believe we have any CI job running without the IDAES solver, so it's possible (but agani, not proven either way) that the `IDAES/idaes-pse` counterpart of this test would fail in the same way if it was run in the same environment (i.e. non-IDAES Ipopt, etc).

**Comment by andrewlee94** [comment]
@adam-a-a Would you be able to run the diagnostics tests (both structural and numeric) and paste the output here? This would help us try to work out what the root cause might be.

Edit: It should not matter which platform you run this on, as the underlying issues will likely be the same.

**Comment by adam-a-a** [comment]
I could do so but currently depend on the GH check for Mac to see results.

**Comment by andrewlee94** [comment]
@adam-a-a Running it on your local machine should be good enough. If there is a modeling issue, it will likely show up no matter what platform you run on; structural issues depend only on the model, and even numerical issues will likely be apparent in the before and after solve runs unless you are really unlucky.

**Comment by andrewlee94** [comment]
@adam-a-a Also, I note you said this could be fixed by re-running the test - is that correct? If so, we are dealing with something more complicated (and something that I am not sure how to deal with).

**Comment by adam-a-a** [comment]
> @adam-a-a Also, I note you said this could be fixed by re-running the test - is that correct? If so, we are dealing with something more complicated (and something that I am not sure how to deal with).

@andrewlee94 I am not certain that this is the case at the moment but can check again.

**Comment by adam-a-a** [comment]
Reminder: we can check if flow_vol_phase in the denominator of the HRT constraint for the WaterTAP CSTR unit is causing an issue. Currently, one of the initialization tests for the WaterTAP CSTR (which adds HRT to the model) is currently failing on Mac checks, but more specifically, when pointing to the latest version of IDAES (v2.6?).

**Comment by lbianchi-lbl** [comment]
The workaround for this issue has been applied in https://github.com/watertap-org/watertap/commit/2919cd6348b7434103aac8d5e7caff327a009f6f#diff-71190dba7803c1fa079436c978ca13ce30a3cc0912477c16033defbbbd43e7a6
