### ISSUE TITLE
Clean up pre-processing for records loaded into EDB

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#156]
Pre-processing of input to be placed in the DB is being split between the database class and the data model classes, which is somewhat messy and confusing. Should either all be in one place or perhaps even pulled out into its own module.

**Comment by aladshaw3** [comment]
@dangunter Can you provide some specific guidance on this issue? I might be able to help clean things up.

**Comment by aladshaw3** [comment]
Code in 2 different modules essentially doing same thing. They should be put into 1 class to remove redundancy.  

Comments somewhere in code about this.

**Comment by dangunter** [comment]
See lines 435-436 in  [watertap.edb.db_api](https://github.com/watertap-org/watertap/blob/main/watertap/edb/db_api.py) module
```
   # XXX: This preprocessing overlaps with data_model.DataWrapper subclasses.
    # XXX: It should all be moved to one place
```

**Comment by aladshaw3** [comment]
> See lines 435-436 in [watertap.edb.db_api](https://github.com/watertap-org/watertap/blob/main/watertap/edb/db_api.py) module
> 
> ```
>    # XXX: This preprocessing overlaps with data_model.DataWrapper subclasses.
>     # XXX: It should all be moved to one place
> ```

@dangunter I am still confused as to why the pre-processing needs to be cleaned up. As far as I can tell, there is only 1 '_preprocess' function under the 'DataWrapper' classes (line 816 [here](https://github.com/watertap-org/watertap/blob/main/watertap/edb/data_model.py)) and no other sub-class of 'DataWrapper' has a preprocess method defined. 

Also, the preprocess method that is defined for the 'Component' object does not perform the same task as the preprocess method in the 'db_api' function call. So I am not sure what the overlap is you are referring to in your comment. 

Is this perhaps something that was already resolved and the comment was just left in place?
