### ISSUE TITLE
Need a 'reload' edb function

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#232]
We have a 'edb load' function, but this function will not load the database if a database already exists. We should have an equivalent 'edb reload' function to drop an existing database and load again.

**Comment by ksbeattie** [comment]
This can already be done with a `edb drop` followed by `edb load`, but a `reload` doing just that could still be useful.

**Comment by aladshaw3** [comment]
Issue deemed unimportant for time being. Closing.
