### ISSUE TITLE
Need to update IDAES tags/fork

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#236]
New IDAES functionality and methods have made there way onto IDAES/main and we need to incorporate this into our chemistry models and update our scaling methods for all chemical models (#235). Once we update our code to build off of the latest IDAES/main, most of the tests that are directly associated with, or depend on the chemistry, will fail. PR #235 should address those failures at that time.

**Comment by lbianchi-lbl** [comment]
I've just sync'ed `watertap-org/idaes-pse` and created the [`1.11.0.watertap.2021.10.11`](https://github.com/watertap-org/idaes-pse/releases/tag/1.11.0.watertap.2021.10.11) tag.

**EDIT** I had initially used the old `proteuslib` name in the tag by mistake, so I deleted that and created the current tab using `watertap` instead.
