### ISSUE TITLE
Resolve scaling and bounds push issues

### ISSUE THREAD

**Issue by bknueven** [watertap-org/watertap#243]
I've collected some thoughts below from #237. While the perturbation helper in #242 will help WaterTAP developers identify when this affects their models, we should decide a standard way forward for WaterTAP models.

# Problem Statement
WaterTAP models often have small (`< 1e-6`) lower bounds and no or much larger upper bounds. The bounds push in IPOPT, [described in the paper on p. 20](http://cepac.cheme.cmu.edu/pasilectures/biegler/ipopt.pdf), will push small initial values on variable with a small LB no or large UB to ~`1e-2` with default settings, sometimes destroying a "good" initialization. In tests I observed that pushing a small variable up a single order of magnitude (e.g., from `1e-6` to `1e-5`)  would cause issues for the RO unit model.

# Potential Solutions

## 1. Selectively apply `bounds_push` when needed
This is essentially our current strategy. With #242 it may become easier to implement, but could become an issue eventually for end-users.

## 2. Change default IPOPT options when `watertap` is imported
We could update `idaes.cfg["ipopt"]["options"]["bound_push"]` when WaterTAP is imported. A value of `1e-08` is needed to initialize the 1DRO model, but a larger global value could be chosen. We can effectively disable IPOPT's bound's pushing by setting `bound_push` small enough, which ensures a model initialized through standard IDAES methods will not have its starting point modified by IPOPT.
#### Potential Pitfalls
Ensuring a strictly feasible primal starting point is necessary for IPOPT's algorithm to work correctly. Not starting at a strict interior point could negatively affect solver performance.

## 3. Write a custom bounds pusher for WaterTAP models
To ensure we start at a strict interior point, we could write a custom bounds pusher for WaterTAP models which is more aware of small values, and then disable IPOPT's bounds pushing.
#### Potential Pitfalls
It's not clear how to incorporate this into every solve without either monkey-patching Pyomo/IDAES when `watertap` is imported or requiring an additional function call before solving a model. Perhaps we could provide our own "solver" by copying the IDAES `get_solver` strategy.

## 4. Be more careful with bounds
- Ensure our models have variable with bounds that are within an order of magnitude
- Variables are unbounded if bounds are not really necessary

## 5. Scaling small values
- Manually scaling some problematic variables in WaterTAP models to avoid small bounds
- Maintaining `user-scaling`.

**Comment by andrewlee94** [comment]
So, this is a case where we probably should be looking at variable scaling, which means the use of `user-scaling` in IPOPT. This of course leads to having to do the Jacobian scaling ourselves (through IDAES' Jacobian scaling tool - this might (should) be straightforward, but we do not have a demonstration of the workflow yet.

**Comment by bknueven** [comment]
Right -- I'm happy to maintain `user-scaling`, though it "doing the Jacobian scaling ourselves" involves an additional function call before `solve`. Obviously not difficult to handle, though it shares a similar pitfall with option (3), which in theory could be done more selectively (i.e., on a per-block basis).

That said, the Jacobin scaling code already exists in IDAES, and hopefully would allow us to use other IDAES modules designed with gradient-based scaling in mind easily.
