### ISSUE TITLE
Issue creating docs locally

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#252]
After installing WaterTAP using `pip install -r requirements-dev.txt`, I received the following error while attempting to create docs locally.

```
(watertap-dev) C:\Users\timvb\idaes\watertap\docs>make html
Running Sphinx v4.2.0
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'li
nkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|m
ath|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '
}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 42 source files that are out of date
updating environment: [new config] 42 added, 0 changed, 0 removed
reading sources... [ 26%] examples/edb/edb_example                             covery
Notebook error:
PandocMissing in examples\edb\edb_example.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
```
Do we need to add pandoc to the requirements file?

**Comment by lbianchi-lbl** [comment]
Thanks for bringing this up @TimBartholomew.

After #244, the `pandoc` executable must be available to be able to build the docs locally. However, it cannot be installed through pip (there is a package called `pandoc` on PyPI, but this is not what is required by the docs), so it has to be installed separately, either through Conda (`conda install -c conda-forge pandoc`), or by following the installation instructions on pandoc's website: https://pandoc.org/installing.html

We're working on the best way to deal with non-`pip install`able dependencies, which might involve creating an `environment-dev.yml` Conda environment file (basically, the Conda equivalent of `requirements-dev.txt`). In the meantime, I can go ahead and add the above text to the developer section in the documentation.
