### ISSUE TITLE
Update documentation on chemistry/EDB examples/tests

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#272]
Some of the documentation is outdated or needs to be cleaned up a bit

- [x] Update the 'How to Scale Chemistry' documentation (outdated information)
- [x] Update the example chemistry flowsheets notes/documents 
- [x] Update EDB 'How to' docs / jupyter notebooks to reflect that fact that MongoDB MUST be installed first
- [x] Remove redundant/unused samples from old flowsheet examples

**Comment by ksbeattie** [comment]
This will follow https://github.com/watertap-org/watertap/pull/270
