### ISSUE TITLE
Coding Style / Code Formatting in WaterTAP

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#280]
Looking over the WaterTAP code, it looks like different people are using different coding styles / formats. Should we all be adhering to a particular style? What is that style? Thoughts/opinions?

**Comment by adam-a-a** [comment]
This was slightly grazed in some comments on my first PR: https://github.com/watertap-org/watertap/pull/45

**Comment by ksbeattie** [comment]
I'll open a PR having run black on all the code and we can see if we like that.

**Comment by ksbeattie** [comment]
Take a look at #281 now.

**Comment by lbianchi-lbl** [comment]
Done in #478 and #482.
