### ISSUE TITLE
WaterTap, Ipopt installment issue for arm64 platform (Apple Silicon)

### ISSUE THREAD

**Issue by lbibl** [watertap-org/watertap#384]
"PIP install" ran extremely slowly (for hours), with a warning message "This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so." It also eventually failed with an error: "ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/3d/68/8bbf0ef969095a13ba0d4c77c1945bd86e9811960d052510551d29a2f23b/jedi-0.12.1-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x108b02440>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"

This issue was resolved by calming Python=3.9 (so it could be an problem with 3.10).  So WaterTap was installed on arm64. 

Ipopt wasn't available in the conda-forge/osx-arm64  channel. 

I found one channel from Anaconda.org having Ipopt and on arm64 platform- https://anaconda.org/TobiasRobotics/ipopt
I did not install  from this channel  because it is not a regular channel. 

I plan to pursue a VM for compilation.  Put this issue here for your information.

**Comment by bknueven** [comment]
Those using osx-arm64 probably need to plan on compiling Ipopt from source for that platform, for now.

**Comment by lbibl** [comment]
I managed to install an ipopt solver from Homebrew : https://formulae.brew.sh/formula/ipopt.   There is also a coincbc for arm64 from conda-forge.  I installed the two.  My environment is now able to pass tests including those in '/unit_models' and solve the unit model I am developing.

**Comment by lbibl** [comment]
To supplement, `ideas environment-info` gives solver info of my environment as the following: Solvers
    bonmin: Not Installed
    cbc: 3.11.4.0
    couenne: Not Installed
    dot_sens: Not Installed
    ipopt: 3.14.5.0
    ipopt_l1: Not Installed
    ipopt_sens: 3.14.5.0
    k_aug: Not Installed

**Comment by lbibl** [comment]
An ipopt from conda-forge for arm64 was tested in a new conda env and WaterTap installment.  Pip installing WaterTAP gave an error of " Failed building wheel for h5py".  Issue was resolved by installing h5py from conda as `conda install h5py`.  The rest of installment was smooth (ipopt and cbc were installed by conda).   `pytest` reported failures on two files: "test_pH_dependent_solubility.py" (error of "infeasible problem") and "test_cryst_prop_pack.py" (error of  "cannot load a SolverResults object with bad status"), and passed all the rest.

**Comment by lbibl** [comment]
Following the installment documentation for MacOS can work for the arm64 chip now.  This issue is thus closed.
