### ISSUE TITLE
Add bounds to zero-order UV costing variables

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#426]
The cost function obtained for UV reactors is a function of inlet flowrate, UV transmittance of the inlet stream, and UV reduced equivalent dosage (PR #414). However, the cost relationship should only be applied within the applicable range of these variables. The upper bound for flowrate, UV transmittance, and UV dose should be 25 MGD, 0.95, and 1000 mJ/cm^2, respectively. 

I tried testing the function out a little bit by calculating cost a little beyond these maxima, and at 25 MGD, 0.97 UV transmittance, and 1000 mJ/cm^2, the cost goes negative. Hence, the costing method in zero_order_costing should likely set the appropriate bounds on these variables or provide a warning to the user if their variable values are out of the applicable range for said cost function. Whatever the case, some kind of solution should be put in place to avoid the function being used in an inapplicable range.

@andrewlee94 What's your take on this?

**Comment by andrewlee94** [comment]
For cases like this, then there do need to be bounds placed on the input variables, however there are some potential catches. I would suggest the following as a starting point:

1. The costing method checks the current value of the input vairables ,and logs a warning if they are out of the bounds.
2. The costing method then sets bounds on the input variables to match the bounds. This suggests that the bounds should be stored in the YAML file as well.

A few other options - there is a way to set ALAMO to use constrained regression that will force certain behaviours outside of the fitted range, but that would take some more work to understand both how to use and what the result would be. The other approach is to manually chose a form, but for this data set it appeared to be rather complicated.

**Comment by luohezhiming** [comment]
We've already upadated the costing method for UV model in PR #700, so this issue has been resolved.
