### ISSUE TITLE
Open a discussion on GitHub Actions / Server Status for Cloud MongoDB 

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#436]
Our documentation has a [how-to](https://watertap.readthedocs.io/en/latest/how_to_guides/how_to_use_EDB.html) section on ways to connect to and utilize the Cloud version of our electrolyte database. At the most recent Electro-chem sub-team meeting we discussed whether or not we want to...

- Test connections to this cloud database through GitHub Actions 
- Provide some form of 'server status' info for the front page of WaterTap 

Are these things that we want to consider? What are the issues in trying to implement something like this?

**Comment by lbianchi-lbl** [comment]
I think both items should be doable with a GitHub Actions workflow running periodically (1/day?), with a status badge that tracks the outcome of the most recent run.

**Comment by aladshaw3** [comment]
> I think both items should be doable with a GitHub Actions workflow running periodically (1/day?), with a status badge that tracks the outcome of the most recent run.

Right now I have a PR that just runs unit tests to test the connection to the cloud server (#466). I'm not sure how to implement a status badge.

**Comment by aladshaw3** [comment]
**NOTE**: This is going to be turned into an EDB example in a Jupyter Notebook

**Comment by aladshaw3** [comment]
Closed by #549
