### ISSUE TITLE
Modification to ion_DSPMDE_prop_pack.py to distinguish ion types

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#458]
IDAES can automatically populate a `cation_set` and `anion_set` is each component in the system is assigned to `.Cation` and `.Anion` at initialization. We should modify the `ion_DSPMDE_prop_pack.py` to iterate through the user provided configuration dict and assign the ions accordingly to built these sets.

**Comment by ksbeattie** [comment]
This is tracked in issue #464
