### ISSUE TITLE
Settling Tank Model Development

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#490]
To Do List:
-----------

- [x] Zero Order Settling Tank [**June**]
   - **Is this even necessary?** IDAES has an ideal separator, which is essentially what this is...
   - Putting it here because it is specifically in the Gantt Chart
   - We have something for this in watertap3 merger... we also have ideal separator in IDAES... is this complete?

- [ ] Create custom zero order settling tank with costing?
   - Something is already in watertap3 merger for this, but maybe we need to make some changes 

- [ ] 0D Settling Tank [**if needed**]
   - NOT explicitly mentioned in Gantt Chart

**Comment by aladshaw3** [comment]
Zero order model has been addressed by watertap3 merger and could also be addressed by IDAES separator.

**Comment by aladshaw3** [comment]
@aladshaw3 Have a look at the sedimentation unit model from watertap3 and see if modifications can be made for more usefulness.

**Comment by adam-a-a** [comment]
There may be a case for a higher fidelity unit to be used as a secondary clarifier for the AMO effort (e.g., 10-layer model). Though not directly tied to the NAWI effort, such a model could be of use. Just something to keep in mind and determine whether such a model would be of general value.

**Comment by aladshaw3** [comment]
Closing this for now. We already have a Z0 settling tank (i.e., ideal separator). If we need something more, we can come back to this later.
