### ISSUE TITLE
Standardize property names

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#513]
Some property packages have different names for the same property (e.g., `pressure_osm` vs `pressure_osm_phase`). This may be confusing to the average user. We should go through all property packages and use standardized names. 

May require some discussion on what names should be used for what property.

**Comment by aladshaw3** [comment]
Here are the names of the properties used in IDAES (from generic property package). I am in favor of sticking to these standardized names for all equivalent properties in our work. 


                "flow_mol": {"method": "_flow_mol"},
                "flow_vol": {"method": "_flow_vol"},
                "flow_mass": {"method": "_flow_mass"},
                "flow_mass_phase": {"method": "_flow_mass_phase"},
                "flow_vol_phase": {"method": "_flow_vol_phase"},
                "flow_mol_phase": {"method": "_flow_mol_phase"},
                "flow_mass_comp": {"method": "_flow_mass_comp"},
                "flow_mol_comp": {"method": "_flow_mol_comp"},
                "flow_mass_phase_comp": {"method": "_flow_mass_phase_comp"},
                "flow_mol_phase_comp": {"method": "_flow_mol_phase_comp"},
                "mole_frac_comp": {"method": "_mole_frac_comp"},
                "mole_frac_phase_comp": {"method": None},
                "phase_frac": {"method": None},
                "temperature": {"method": None},
                "pressure": {"method": None},
                "act_phase_comp": {"method": "_act_phase_comp"},
                "act_phase_comp_true": {"method": "_act_phase_comp_true"},
                "act_phase_comp_apparent": {"method": "_act_phase_comp_apparent"},
                "act_coeff_phase_comp": {"method": "_act_coeff_phase_comp"},
                "act_coeff_phase_comp_true": {"method": "_act_coeff_phase_comp_true"},
                "act_coeff_phase_comp_apparent": {
                    "method": "_act_coeff_phase_comp_apparent"
                },
                "compress_fact_phase": {"method": "_compress_fact_phase"},
                "conc_mol_comp": {"method": "_conc_mol_comp"},
                "conc_mol_phase_comp": {"method": "_conc_mol_phase_comp"},
                "conc_mol_phase_comp_apparent": {
                    "method": "_conc_mol_phase_comp_apparent"
                },
                "conc_mol_phase_comp_true": {"method": "_conc_mol_phase_comp_true"},
                "cp_mol": {"method": "_cp_mol"},
                "cp_mol_phase": {"method": "_cp_mol_phase"},
                "cp_mol_phase_comp": {"method": "_cp_mol_phase_comp"},
                "cv_mol": {"method": "_cv_mol"},
                "cv_mol_phase": {"method": "_cv_mol_phase"},
                "cv_mol_phase_comp": {"method": "_cv_mol_phase_comp"},
                "diffus_phase_comp": {"method": "_diffus_phase_comp"},
                "diffus_phase_comp_apparent": {"method": "_diffus_phase_comp_apparent"},
                "diffus_phase_comp_true": {"method": "_diffus_phase_comp_true"},
                "heat_capacity_ratio_phase": {"method": "_heat_capacity_ratio_phase"},
                "dens_mass": {"method": "_dens_mass"},
                "dens_mass_phase": {"method": "_dens_mass_phase"},
                "dens_mol": {"method": "_dens_mol"},
                "dens_mol_phase": {"method": "_dens_mol_phase"},
                "energy_internal_mol": {"method": "_energy_internal_mol"},
                "energy_internal_mol_phase": {"method": "_energy_internal_mol_phase"},
                "energy_internal_mol_phase_comp": {
                    "method": "_energy_internal_mol_phase_comp"
                },
                "enth_mol": {"method": "_enth_mol"},
                "enth_mol_phase": {"method": "_enth_mol_phase"},
                "enth_mol_phase_comp": {"method": "_enth_mol_phase_comp"},
                "entr_mol": {"method": "_entr_mol"},
                "entr_mol_phase": {"method": "_entr_mol_phase"},
                "entr_mol_phase_comp": {"method": "_entr_mol_phase_comp"},
                "fug_phase_comp": {"method": "_fug_phase_comp"},
                "fug_coeff_phase_comp": {"method": "_fug_coeff_phase_comp"},
                "gibbs_mol": {"method": "_gibbs_mol"},
                "gibbs_mol_phase": {"method": "_gibbs_mol_phase"},
                "gibbs_mol_phase_comp": {"method": "_gibbs_mol_phase_comp"},
                "isentropic_speed_sound_phase": {
                    "method": "_isentropic_speed_sound_phase"
                },
                "isothermal_speed_sound_phase": {
                    "method": "_isothermal_speed_sound_phase"
                },
                "henry": {"method": "_henry"},
                "mass_frac_phase_comp": {"method": "_mass_frac_phase_comp"},
                "mass_frac_phase_comp_apparent": {
                    "method": "_mass_frac_phase_comp_apparent"
                },
                "mass_frac_phase_comp_true": {"method": "_mass_frac_phase_comp_true"},
                "molality_phase_comp": {"method": "_molality_phase_comp"},
                "molality_phase_comp_apparent": {
                    "method": "_molality_phase_comp_apparent"
                },
                "molality_phase_comp_true": {"method": "_molality_phase_comp_true"},
                "mw": {"method": "_mw"},
                "mw_comp": {"method": "_mw_comp"},
                "mw_phase": {"method": "_mw_phase"},
                "pressure_phase_comp": {"method": "_pressure_phase_comp"},
                "pressure_phase_comp_true": {"method": "_pressure_phase_comp_true"},
                "pressure_phase_comp_apparent": {
                    "method": "_pressure_phase_comp_apparent"
                },
                "pressure_bubble": {"method": "_pressure_bubble"},
                "pressure_dew": {"method": "_pressure_dew"},
                "pressure_osm_phase": {"method": "_pressure_osm_phase"},
                "pressure_sat_comp": {"method": "_pressure_sat_comp"},
                "surf_tens_phase": {"method": "_surf_tens_phase"},
                "temperature_bubble": {"method": "_temperature_bubble"},
                "temperature_dew": {"method": "_temperature_dew"},
                "therm_cond_phase": {"method": "_therm_cond_phase"},
                "visc_d_phase": {"method": "_visc_d_phase"},
                "vol_mol_phase": {"method": "_vol_mol_phase"},
                "vol_mol_phase_comp": {"method": "_vol_mol_phase_comp"},
                "dh_rxn": {"method": "_dh_rxn"},
                "log_act_phase_comp": {"method": "_log_act_phase_comp"},
                "log_act_phase_solvents": {"method": "_log_act_phase_solvents"},
                "log_act_phase_comp_true": {"method": "_log_act_phase_comp_true"},
                "log_act_phase_comp_apparent": {
                    "method": "_log_act_phase_comp_apparent"
                },
                "log_conc_mol_phase_comp": {"method": "_log_conc_mol_phase_comp"},
                "log_conc_mol_phase_comp_true": {
                    "method": "_log_conc_mol_phase_comp_true"
                },
                "log_mass_frac_phase_comp": {"method": "_log_mass_frac_phase_comp"},
                "log_mass_frac_phase_comp_apparent": {
                    "method": "_log_mass_frac_phase_comp_apparent"
                },
                "log_mass_frac_phase_comp_true": {
                    "method": "_log_mass_frac_phase_comp_true"
                },
                "log_molality_phase_comp": {"method": "_log_molality_phase_comp"},
                "log_molality_phase_comp_apparent": {
                    "method": "_log_molality_phase_comp_apparent"
                },
                "log_molality_phase_comp_true": {
                    "method": "_log_molality_phase_comp_true"
                },
                "log_mole_frac_comp": {"method": "_log_mole_frac_comp"},
                "log_mole_frac_tbub": {"method": "_log_mole_frac_tbub"},
                "log_mole_frac_tdew": {"method": "_log_mole_frac_tdew"},
                "log_mole_frac_pbub": {"method": "_log_mole_frac_pbub"},
                "log_mole_frac_pdew": {"method": "_log_mole_frac_pdew"},
                "log_mole_frac_phase_comp": {"method": "_log_mole_frac_phase_comp"},
                "log_mole_frac_phase_comp_apparent": {
                    "method": "_log_mole_frac_phase_comp_apparent"
                },
                "log_mole_frac_phase_comp_true": {
                    "method": "_log_mole_frac_phase_comp_true"
                },
                "log_pressure_phase_comp": {"method": "_log_pressure_phase_comp"},
                "log_pressure_phase_comp_apparent": {
                    "method": "_log_pressure_phase_comp_apparent"
                },
                "log_pressure_phase_comp_true": {
                    "method": "_log_pressure_phase_comp_true"
                },
                "log_k_eq": {"method": "_log_k_eq"},

**Comment by dangunter** [comment]
All names follow the [standard IDAES naming conventions](https://idaes-pse.readthedocs.io/en/stable/explanations/conventions.html#standard-naming-format)

**Comment by dangunter** [comment]
Also ,though why is moles spelled like "mole" in a few of the IDAES examples? `log_mole_frac_comp` , tbub, tdew etc.?

**Comment by dangunter** [comment]
And, sorry, but is "molality" part of the convention? The standard says mol = "Molar basis". So is "molality" = "Molal basis" (or is that just nonsense)?

**Comment by andrewlee94** [comment]
@dangunter Semantics. The unit is `mol` (which is the same singular and plural) - "mole" on the other hand is a quantity. To clarify, mole is the quantity and mol is the units in  the same way that power is a quantity with units Watts. In this sense, "mole_frac" indicates "mole fraction" (i.e. moles of species per mole of mixture).

Molarity means "concentration on a molar basis" (i.e. moles per unit volume) and molar is means a measure of moles. Molal and molality are a different quantity (moles per unit mass).

**Comment by dangunter** [comment]
Should we add "mole_frac" (and I guess phase_frac and therefore "*_frac", but mole_frac seems like a special case worth calling out) and "molality" to the IDAES docs page?

**Comment by andrewlee94** [comment]
Both are already in there I believe.
