### ISSUE TITLE
Use ":" instead of "-" inside args in docstrings

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#525]
@bknueven and @OOAmusat , to avoid errors when building pretty HTML of the source code for the documentation, please use this style when listing multiple arguments:

```
Args:
    arg1: Description that is very long and goes onto a second
        line, which is indented by a tab.
    arg2: Another description
    `**kwargs`: These are sort of special, and are backquoted so they don't look like a bulleted list
```

Sometimes, using dashes and deeper indentation causes errors in the HTML build.
[This page of examples from the Napoleon Sphinx plugin](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) has examples that you can imitate (for things not covered above).

I am mentioning this because when the HTML build fails, the test suite fails, so this will prevent trivial formatting issues from wasting your time re-running the tests.

**Comment by ksbeattie** [comment]
We could create a watertap specific wiki page about our standard on formatting docstrings.  Or perhaps look into if pylint can enforce this?
