### ISSUE TITLE
Address doctest failures due to IDAES v2 deprecations

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#543]
- Changes recently introduced in IDAES cause some of the doctests to fail
- In order to merge #520, we're temporarily disabling the doctest check in the GHA CI workflow

## TODO

- [ ] Re-enable doctest check ASAP to avoid false negatives in the documentation code snippets
- [ ] Get rid of the deprecation messages by updating the import paths throughout the WaterTAP codebase

##### Use `.. doctest::` instead of `.. testcode::` for doctests that do not require testing the output

- Most if not all of the doctests are specified using the `.. testcode::` directive
- As I understand, this is supposed to be used in combination with a `.. testoutput::` block containing the expected output to be compared with the output of the code block (see the [testcode section in the sphinx-doctest documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-testcode) for more info)
- If no `.. testoutput::` is present, the code block is assumed to produce no output, which might or might not be what we want
- If we don't care about the output, we should consider converting all "lonely" `.. testcode::` directives to use `.. doctest::` instead

##### `stdout` vs `stderr` for IDAES deprecation messages

- I haven't realized this until now, but apparently the IDAES deprecation messages are emitted on `stdout`
- I'm not sure if there was a motivation behind this choice, but it could be argued that the IDAES deprecation messages should be emitted to `stderr` instead
- In any case, this is something that should be addressed at the IDAES level rather than by WaterTAP

**Comment by andrewlee94** [comment]
@lbianchi-lbl On the deprecation messages being emitted to `stdout`, I think that is actually a Pyomo decision as we are doing all deprecations through Pyomo functions. These functions do not take a stream as an argument (or at least we are not providing one), so I am assuming that Pyomo set the output as `stdout`.
