### ISSUE TITLE
Extensions to dye desalination example

### ISSUE THREAD

**Issue by arao53** [watertap-org/watertap#575]
### Summary 
The dye desalination example flowsheets have some slight discrepancies that would be good to resolve. These include more overlap between the two flowsheets and their sweeps (with and without RO), cost optimization of RO, and 0 value parameter errors.

### To Do
- [x] Resolve differences in cost metrics between dye_desalination.py and dye_desalination_withRO.py
- [x] Edit dye_sweep.py to account for sweeps with both flowsheets.
- [x] Add sweeps for dye_desalination_withRO
- [x] Implement setup_optimization method to optimize RO costs
- [ ] Resolve error with 0 value parameters, possibly by converting expressions to constraints. (#574 )

**Comment by adam-a-a** [comment]
This issue has been resolved. The only remaining task is actually an issue in Pyomo (https://github.com/Pyomo/pyomo/issues/1627)
