### ISSUE TITLE
Electrodialysis Refinement - Sept

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#593]
Refine electrodialysis model
- [x] Build a flowsheet for a ED-focused publication (start from a simple design) 
- [x] Improve scaling in 1-D (to better handle length variation) 
- [x] Add water recovery factor to calculate the inlet flow ration between two channels. (Would be applied at a splitter BEFORE the unit model)
- [x] Convert from cell_pair to stack 
- [x ] Add a method to calculate limiting current from water salinity (one method is on; two other methods are planned to do)
- [x] Simple improvement: equivalent conductance calculation. 
- [x] Simulate interfacial potential distribution to evaluate non-ohmic resistance. (User config option, off by default) 1D and 0D.

**Comment by lbibl** [comment]
PR #745,  #744,  #768, #774 check the last box.
