### ISSUE TITLE
More updates for property packages

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#605]
It was pointed out in #564 that there are still some outstanding issues with standardization of properties. Below is a brief summary of additional things to address:

- [ ] Calculation of Schmidt number (`N_Sc`) in `_reverse_osmosis_base` needs to be indexed by component because it can be either NaCl or TDS or other depending on the package invoked
      - Connected to #876 
- [x] While all property names have been updated to have corresponding indices for phase/comp, this is still not reflected by the actual constraints. All constraints should have same indices as the variables they calculate. 
      - Connected to #309 
- [x] Several property packages have 'hard-coded' phase/comp names in their constraints. This should be changed to use `p` and `j`, for phase and component, respectively. Do not hard-code names of phases and comps if avoidable.

**Comment by TimBartholomew** [comment]
@MarcusHolly I believe you are currently addressing the last 2 check boxes, you can also probably put the top check box on your to do list. If you have questions about what Austin was describing, I'd be happy to meet.

**Comment by MarcusHolly** [comment]
> 
@TimBartholomew I'll take a look at this again tomorrow and see if my time away from it has somehow granted me some additional insight. But most likely, I will still have questions so maybe we could meet sometime early next week?

**Comment by TimBartholomew** [comment]
The RO model is single component, so it's probably fine that we do not index it by component. Although, maybe we want to preemptively index it by component to match other models that are multicomponent like NF and ED.

**Comment by TimBartholomew** [comment]
@MarcusHolly I'm now thinking we may just want to index N_Sc by component (i.e. N_Sc_comp). Just so that we have it standardized, even though there is only one component for reverse osmosis. It wouldn't be a too difficult change right?
