### ISSUE TITLE
Add static checking using Pylint

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#620]
Partially inspired by #609, but useful also for other things.

Following @ksbeattie's (IIRC) suggestion, I think the best thing would be starting from an opt-in strategy, i.e. disable all checks by default, and enable the subset of checks that we want to enforce one at a time.

Full list of checks/possible errors (somewhat confusingly, called "messages" in Pylint): https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html

**Comment by ksbeattie** [comment]
Partially addressed by #822 and #821
