### ISSUE TITLE
Making AMO flowsheets and multi-sweep files more user friendly

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#621]
The following changes can be made in most, if not all, AMO flowsheets:
- [ ] Instead of `assert_optimal_termination` in main(), consider replacing with `check_optimal_termination` and more helpful error message for user
- [ ] Add more user-friendly usage notes for running multi-sweep from command line. Example:
https://github.com/watertap-org/watertap/blob/92f6ab39ef3cd4a350f31c4edcee0656831849f1/watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/multi_sweep.py#L83-L92

**Comment by adam-a-a** [comment]
Simple cleanup, up for grabs.

**Comment by bknueven** [comment]
Since this will slip the September release: should we be creating a general runner for the multi-sweeps? Seems like they all replicate a bunch of code.

**Comment by dangunter** [comment]
For the UI layer I will probably follow the pattern in fsapi.py and have some Pydantic objects to wrap the parameter sweep functionality -- inputs and outputs -- e.g., allowing the following workflow:
```
inputs = ParameterSweepInput(<keywords can go here>)
inputs.set_something(value), ..etc..
psw = ParameterSweepRunner()
results = psw.run(inputs)  # where 'result' is another object that can be serialized or iterated
```
