### ISSUE TITLE
Revisit GAC scaling and other issues

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#625]
Corresponding PR #626 
It was discovered in #559 that the scaling implemented for the GAC model may be too simplified. 

- [x] Revisit the scaling values used for the model variables
- [x] ~~Add scaling for model constraints~~

Other issues include:

- [x] Tolerance used for testing simplified solution is way too loose
      - Currently using a tolerance of 0.1 for comparison. This needs to be at least 1e-3. 
      - Line 207 in `test_solution_simplified`
  
- [x] Remove the `within` keyword arg for Param `saturation_mtz_upstream`
      - Not proper Param definition in Pyomo
      - Line 251 from `gac.py`

**Comment by hunterbarber** [comment]
@adam-a-a Wasn't it identified that all constraint scaling is handled internally to the solver and therefore not required in unit models?

**Comment by adam-a-a** [comment]
Right, especially using ipopt-watertap, constraint scaling isn't _always_ needed although there may be cases where it could help. @bknueven could probably say more about this.

**Comment by adam-a-a** [comment]
@hunterbarber One thing I'd like to see with any further work related to GAC is simply an example relevant to PFOS/PFOA removal. While it should only hypothetically require parameter data to do so, I think _some_ example relevant to our application of interest would be a nice subsequent step. Just wanted to note this under an issue to track, and this seemed like the best place. I realize that this can be done while considering a more complex example with a multicomponent model, but even a simple example with PFOS/PFOA as the single component of interest would be nice to have.

**Comment by hunterbarber** [comment]
> @hunterbarber One thing I'd like to see with any further work related to GAC is simply an example relevant to PFOS/PFOA removal. While it should only hypothetically require parameter data to do so, I think _some_ example relevant to our application of interest would be a nice subsequent step. Just wanted to note this under an issue to track, and this seemed like the best place. I realize that this can be done while considering a more complex example with a multicomponent model, but even a simple example with PFOS/PFOA as the single component of interest would be nice to have.

I agree and think it may be best considered in a subsequent flowsheet example considering the relevancy.
