### ISSUE TITLE
UV AOP deprecation warnings

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#628]
I recently pulled from main and reinstalled WaterTAP and any script in the examples folder that I run has deprecation warnings from uv_aop. Below is the output after running:
`python .\watertap\examples\flowsheets\RO_with_energy_recovery\RO_with_energy_recovery.py`
The warnings on the flow_expr and scaling factor are expected.

```
WARNING: DEPRECATED: the 'get_solver' function has been moved to
    'idaes.core.solvers.get_solver'.  Please update your import. (deprecated
    in 2.0.0.alpha0) (called from
    c:\users\tim\idaes\watertap\watertap\unit_models\uv_aop.py:38)
WARNING: DEPRECATED: the 'DistributedVars' class has been moved to
    'idaes.core.base.control_volume1d.DistributedVars'.  Please update your
    import.  (deprecated in 2.0.0.alpha0) (called from <frozen
    importlib._bootstrap>:219)
2022-07-19 09:52:06 [WARNING] idaes.core.base.costing_base: flow_expr is an expression with a lower bound of less than zero. Costing requires that all flows have a lower bound equal to or greater than zero to
 avoid negative costs.
2022-07-19 09:52:06 [WARNING] idaes.core.base.costing_base: flow_expr is an expression with a lower bound of less than zero. Costing requires that all flows have a lower bound equal to or greater than zero to
 avoid negative costs.
2022-07-19 09:52:06 [WARNING] idaes.core.util.scaling: Missing scaling factor for fs.RO.area
WARNING: DEPRECATED: the 'get_solver' function has been moved to
    'idaes.core.solvers.get_solver'.  Please update your import. (deprecated
    in 2.0.0.alpha0) (called from
    c:\users\tim\idaes\watertap\watertap\unit_models\uv_aop.py:38)
WARNING: DEPRECATED: the 'DistributedVars' class has been moved to
    'idaes.core.base.control_volume1d.DistributedVars'.  Please update your
    import.  (deprecated in 2.0.0.alpha0) (called from <frozen
    importlib._bootstrap>:219)
```
I understand how to fix the get_solver one, I'm not so sure on the distributed vars, but my main question is why is it being ran? I think this means that there is something out there that runs UV_AOP on import? Interestingly, I always receive two sets of the deprecation warnings, so it seems to be called twice.

**Comment by lbianchi-lbl** [comment]
@TimBartholomew from a quick look, I think `watertap.unit_models.uv_aop` is being imported in `watertap.unit_models.__init__`, and therefore all the module-level code in `uv_aop` is executed whenever you import from `watertap.unit_models` (i.e. including unit models that are not `uv_aop`):

https://github.com/watertap-org/watertap/blob/5336ae5c728edd6112b5c9a13b25bfb258b14010/watertap/unit_models/__init__.py#L20-L22

**Comment by andrewlee94** [comment]
Following on from @lbianchi-lbl, one of those models is then importing the `DistributedVars` class and needs to update the path it is using.
