### ISSUE TITLE
Probe ion property model usage with pump unit

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#634]
@lbibl reported an issue when using the ion property model with a Pump unit, due to enthalpy balance being excluded in the ion property model. This brings up a good point -- I don't think we've done any testing of the ion property model in a flowsheet nor with pump units until now. Previously, it was only used for the NF DSPM-DE, GAC, and IX unit models. 

We should take a look at this and probe for a solution as needed. One solution is to add an enthalpy balance to the property model. Another solution might entail setting the right pump config argument or using an alternative pump unit model (e.g., zero-order versions, which might introduce other complications for flowsheet development though).

**Comment by adam-a-a** [comment]
@luohezhiming also reported an issue when trying to use ion property model with his UV-AOP model:

>  I cannot directly use the ion prop package, an error with idaes.core.util.exceptions.PropertyNotSupportedError: fs.unit.control_volume.properties_out[0.0] package property metadata method does not contain a method for default_energy_balance_type. Please select a package which supports the necessary properties for your process.

**Comment by lbibl** [comment]
@luohezhiming can try setting `energy_balance_type.None` somewhere (in the unit or test file) if the energy balance constraint isn't actually useful or can be manually coded.   Meanwhile, to note the conclusion from our Electrochem meeting,  I can try adding an enthalpy flow into the DSPMDE ion pp in a similar manner to the NaCl ion property pack and enable the energy balance constraint.  But we'll need  to be cautious about the method's theoretical correctness when it's used case by case.  I will also make more investigation into the theoretical side of "enthalpy flow" in water solution cases.

**Comment by luohezhiming** [comment]
@lbibl Thank you, can you clarify how can I set `energy_balance_type.none` in the test file?

**Comment by lbibl** [comment]
> @luohezhiming can try setting `energy_balance_type.None` somewhere (in the unit or test file) if the energy balance constraint isn't actually useful or can be manually coded. Meanwhile, to note the conclusion from our Electrochem meeting, I can try adding an enthalpy flow into the DSPMDE ion pp in a similar manner to the NaCl ion property pack and enable the energy balance constraint. But we'll need to be cautious about the method's theoretical correctness when it's used case by case. I will also make more investigation into the theoretical side of "enthalpy flow" in water solution cases.

I took a look at your uv_aop from your fork and recommend the following: 1) investigate if your unit mode needs an energy balance constraint by principle  (e.g., does your model handle any energy changes carried by the solution?)  2) if "No" to 1) or the energy conservation can be replaced by an isothermal (Tin = Tout) constraint, you can try  a) setting the "energy_balance_type" in the configuration default to `.None` instead of `.UseDefault` and removing the `control_volume.add_energy_balance()` constraint;  b) keeping  `.UseDefault`, but  when you do `add_energy_balances()`  , setting `has_enthalpy_transfer = False`.  So if you set default to `.None` in the configuration, `add_energy_balances()` will actually be meaningless and can be deleted.  But you can try what happens if you set `.UseDefault`  but give `has_enthalpy_transfer = False`.  I can look into more if you need.

**Comment by luohezhiming** [comment]
@lbibl I set the energy balance config with `EnergyBalanceType.none`, then it works. But I have another error: `AttributeError: 'ScalarPort' object has no attribute 'flow_mass_phase_comp'` when I try to specify the inlet mass flow as: ```
m.fs.unit.inlet.flow_mass_phase_comp[0, "Liq", "NDMA"].fix(
            feed_flow_mass * feed_mass_frac_NDMA
        
```)

**Comment by lbibl** [comment]
> > @luohezhiming can try setting `energy_balance_type.None` somewhere (in the unit or test file) if the energy balance constraint isn't actually useful or can be manually coded. Meanwhile, to note the conclusion from our Electrochem meeting, I can try adding an enthalpy flow into the DSPMDE ion pp in a similar manner to the NaCl ion property pack and enable the energy balance constraint. But we'll need to be cautious about the method's theoretical correctness when it's used case by case. I will also make more investigation into the theoretical side of "enthalpy flow" in water solution cases.
> 
> I took a look at your uv_aop from your fork and recommend the following: 1) investigate if your unit mode needs an energy balance constraint by principle (e.g., does your model handle any energy changes carried by the solution?) 2) if "No" to 1) or the energy conservation can be replaced by an isothermal (Tin = Tout) constraint, you can try a) setting the "energy_balance_type" in the configuration default to `.None` instead of `.UseDefault` and removing the `control_volume.add_energy_balance()` constraint; b) keeping `.UseDefault`, but when you do `add_energy_balances()` , setting `has_enthalpy_transfer = False`. So if you set default to `.None` in the configuration, `add_energy_balances()` will actually be meaningless and can be deleted. But you can try what happens if you set `.UseDefault` but give `has_enthalpy_transfer = False`. I can look into more if you need.

These can also be performed by assigning the `energy_balance_type` to `None` configure to none when you add your unit block to your flowsheet in a test file.

**Comment by lbibl** [comment]
> @lbibl I set the energy balance config with `EnergyBalanceType.none`, then it works. But I have another error: `AttributeError: 'ScalarPort' object has no attribute 'flow_mass_phase_comp'` when I try to specify the inlet mass flow as: ``` m.fs.unit.inlet.flow_mass_phase_comp[0, "Liq", "NDMA"].fix( feed_flow_mass * feed_mass_frac_NDMA

This is due to that the DSPMDE pp uses `flow_mol_phase_comp` as state_var instead of `flow_mass_phase_comp`.  So it will work if you fix `flow_mol_phase_comp`.  Can you run your model molar_based?   I think there is also a way to fix mass flow and calculate the molar flow but you may make the model larger.  I have not tested this and plan to discuss potential changes to the DSPMDE pp in the electrochem meeting to let it handle mass_based input better.

**Comment by luohezhiming** [comment]
@lbibl I set the config of energy_balance with `EnergyBalanceType.none`. Everything works well except for running `calculate_scaling_factors(m)`, I got an error as: `AttributeError: '_ScalarControlVolume0DBlock' object has no attribute 'enthalpy_transfer'`. Do you know if there is a way to fix that?

**Comment by luohezhiming** [comment]
> @lbibl I set the config of energy_balance with `EnergyBalanceType.none`. Everything works well except for running `calculate_scaling_factors(m)`, I got an error as: `AttributeError: '_ScalarControlVolume0DBlock' object has no attribute 'enthalpy_transfer'`. Do you know if there is a way to fix that?

@lbibl I've resolved the problem, I should also delete those scaling factor calculation equations for enthalpy transfer. Everything works right now.

**Comment by adam-a-a** [comment]
This issue is related to the discussion in issue #651

**Comment by adam-a-a** [comment]
This issue was primarily resolved by my PR in IDAES: https://github.com/IDAES/idaes-pse/pull/925
