### ISSUE TITLE
Untracked .csv files produced when running all pytests

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#642]
Just tested out new installation of WaterTAP on an Ubuntu WSL and ran all pytests. Noticed that a significant number of `.csv` files get produced in the `examples/flowsheets/case_studies` files when pytest is run. It is annoying because `git` keeps seeing these files as untracked changes and I find I have to manually delete these files to remove all the red 'untracked file' warnings. 

Do we need to keep these files after pytests have finished running? Should these `sensitivity_*.csv` files be automatically removed after the tests pass? Or is there a way to use the `.gitignore` file to just ignore these as untracked files?

**Comment by andrewlee94** [comment]
@aladshaw3 I agree that tests need to clean up after themselves and this should be fixed.

Something that might help in the meantime however is `git clean -df` - this will clean up all untracked files and folders in the repo in one go (be careful however as it will clean ALL untracked files). You can use the `-n` flag to do a dry-run and see what would be cleaned up before running the actual command.
