### ISSUE TITLE
Move location of persistently constructed variables within corresponding on-demand properties and functions

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#657]
When using various property packages, enth_mass_param, diffus_param, and dens_mass_param may be constructed for on-demand properties even when the property itself is not constructed. This leads to nonzero `number_unused_variables()` in many tests due to exclusively property package variables and may lead to complications in other utility functions.

Similarly, this occurs in the costing package where all costing parameters are constructed at the highest level where only a subset tied to the used unit models are needed. In this case, it would be more of a change to improve conciseness of the model and reporting.

**Comment by andrewlee94** [comment]
Is there any really issue with having unused variables in the problem however (especially in the case of tests)? Unused variables do not get sent to the solve (at least for the NL writer), so they do not effect the tractability of the problem.

**Comment by hunterbarber** [comment]
> Is there any really issue with having unused variables in the problem however (especially in the case of tests)? Unused variables do not get sent to the solve (at least for the NL writer), so they do not effect the tractability of the problem.

They do however get accounted for in any utility tool that uses `component_data_object(m)` or any similar function concerning model analytics if I'm not mistaken. The costing package would be almost exclusively for better visualization of model variables when reporting `m.fs.costing` results.

**Comment by andrewlee94** [comment]
A couple of general responses:

1. Yes, they will show up in `component_objects` and `component_data_objects`, but there are ways to deal with this (e.g. the `number_unused_variables` method in `model_statistics`).
2. "build-on-demand" variables, whilst possible, are a pain to set up and test robustly. It is better to avoid this wherever possible, even if it means having a few unused variables hanging around (and there are other cases where these will show up anyway , e.g. 1D control volumes).

**Comment by lbibl** [comment]
From my experience, extra variables can be created because of they are used to calculate the on-demand variables, in which case I don't think they are counted as "unused var" (correct me if I am wrong) and they can be just treated as internal variables making the code smooth/efficient.  I recently fixed another scenario in the DMDSPE ion p.p. ,where extra variables were created due to the missing of `is_constructed` conditional statement.  I in general agree with @andrewlee94 that there are ok to exist as long as they do not mess up with solving .

**Comment by hunterbarber** [comment]
Better posed in #676
