### ISSUE TITLE
Implement test_harness to reduce repetition in 0DRO testing

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#66]
Due to the additional configuration options being added to the 0D RO model, the test file has a lot of repeated code that could be reduced by implementing test_harness.

**Comment by wigging** [comment]
@adam-a-a Are you referring to the tests in `watertap/unit_models/tests/test_reverse_osmosis_0D.py`?

**Comment by MarcusHolly** [comment]
Resolved in #1277
