### ISSUE TITLE
Call GAC property variables from ion_DSPMDE_prop_pack and other GAC changes

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#683]
Move any properties constructed in gac.py to corresponding property package model, DSPMDE_prop_pack. This includes:

High Priority:
- [ ] allow for multi-species adsorption using the ideal adsorbed solution theory (IAST)
- [x] Remove redundant equation with circular reference causing failure depending on set of fixed variables
- [ ] call molecular diffusion coefficient from prop pack
- [ ] embed molar volume calculation

Low Priority:
- [x] update lb of `gac.equil_conc`
- [ ] dynamic sf for `gac.equil_conc` as f(`inlet_conc`) 
- [x] correct line 1144 for reporting of molar flowrate to port
- [x] correct typo in Schmidt number doc string
- [ ] implement check for `gac.length_mtz` size being approximately ≤ `gac.bed_length`
- [x] Add bed diameter as relevant sizing variable

**Comment by lbibl** [comment]
FYI I am working on adding quite a few things into the DSPMDE ion property package.  So we may wanna pay some attention to which goes first (either order would work).   Is the "molecular diffusion coefficient" the one for species (ion or neutral) in solution and carrying a unit of [m2/s] ?  If yes, it already exists as `diffus_phase_comp` and its value is passed in by the `diffusivity_data` config.

**Comment by hunterbarber** [comment]
> FYI I am working on adding quite a few things into the DSPMDE ion property package. So we may wanna pay some attention to which goes first (either order would work). Is the "molecular diffusion coefficient" the one for species (ion or neutral) in solution and carrying a unit of [m2/s] ? If yes, it already exists as `diffus_phase_comp` and its value is passed in by the `diffusivity_data` config.

The PR #626 up for GAC enhancements is ready to be merged, but after that merge I'll do a full sweep on the variables constructed and coordinate with you on what is directly applicable or may be of use to add. This can then be handled in a subsequent PR. Thanks for taking a look.

**Comment by hunterbarber** [comment]
Pending merger of #699 to convert variable over and assess further prop pack needs

**Comment by ksbeattie** [comment]
@hunterbarber is this closable now?

**Comment by hunterbarber** [comment]
> @hunterbarber is this closable now?

Some of these changes have been made but are not pushed. Others have not yet been handled. This will likely be tackled before the end of December.
