### ISSUE TITLE
Remove examples directory

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#712]
The sole purpose of the examples directory was to hold some sample flowsheets with an interface used by the UI. These examples have been moved to a more convenient place in the watertap-ui repo, so this directory can now be removed.

**Comment by wigging** [comment]
I see several folders containing examples (see list below). I suggest putting everything into a single `watertap/examples` directory and getting rid of `watertap/tutorials` and `watertap/watertap/examples`.
- `watertap/examples`
- `watertap/tutorials`
- `watertap/watertap/examples`
