### ISSUE TITLE
Replace ValueError with InitializationError in check_solve

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#715]
Instead of raising a `ValueError ` in `watertap.core.util.initialization.check_solve`, consider raising `InitializationError` instead.

Also consider whether this is applicable to other functions in the `watertap.core.util.initialization` module.

**Comment by MarcusHolly** [comment]
@adam-a-a This has not been addressed by PR #807. While the changes seem pretty quick and straightforward, I'm not completely sure what the advantage would be to raising an `InitializationError` over a `ValueError`. If `watertap.core.util.initialization.check_solve` fails, does that necessarily mean there is an error in the initialization? I suppose what I'm getting at is what's the reason we raised a `ValueError` in the first place?
