### ISSUE TITLE
Electrocoagulation model development

### ISSUE THREAD

**Issue by srikanthallu** [watertap-org/watertap#739]
- [x] Implement Phenomenological model for EC
- [x] Implement Costing for EC
- [x] EC Documentation
- [ ] Demonstration of EC in flowsheet

**Comment by wigging** [comment]
@srikanthallu Any updates on this? Have you implemented the model in watertap?

**Comment by srikanthallu** [comment]
No, I have not. From last I remember we are waiting on the costing model and energy consumption estimates from Analysis team to close the loop.

**Comment by wigging** [comment]
Did you decide to use the zero-order modeling approach for this?

**Comment by ksbeattie** [comment]
Addressed in #953
