### ISSUE TITLE
Fix incorrect use of `.. doctest::` directive in documentation

### ISSUE THREAD

**Issue by bknueven** [watertap-org/watertap#746]
In most places, `.. doctest::` should instead be `.. testcode::`.

Currently, lots of code-blocks in the documentation are not getting tested.

**Comment by wigging** [comment]
I can start working on this tomorrow (Friday, Sept. 23) unless @bknueven has already started on it.

**Comment by bknueven** [comment]
@wigging feel free to start -- I would get to this next week at the earliest.

**Comment by wigging** [comment]
Can @bknueven or @lbianchi-lbl close this issue? It was fixed with the merged pull request.
