### ISSUE TITLE
Add diagrams for peracetic, hrcs, magprex

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#825]
### Description

Add diagrams for peracetic acid disinfection, hrcs, magprex

### Motivation

Otherwise it says "no diagram found" in GUI

**Comment by dangunter** [comment]
@TimBartholomew and @adam-a-a can you identify people to provide the diagrams for these 3 flowsheets?

**Comment by MichaelPesce** [comment]
@MarcusHolly I looked into this, it appears only the peracetic flowsheet has a misnamed diagram file (peracetic_acid_ui.png, should be peracetic_acid_disinfection_ui.png). The other 2 diagrams should be working as far as I can tell. Seems to be a bug on the UI end that is causing them not to show up

**Comment by MarcusHolly** [comment]
> @MarcusHolly I looked into this, it appears only the peracetic flowsheet has a misnamed diagram file (peracetic_acid_ui.png, should be peracetic_acid_disinfection_ui.png). The other 2 diagrams should be working as far as I can tell. Seems to be a bug on the UI end that is causing them not to show up

Great, thx. Just let me know if there's anything I can help with.
