### ISSUE TITLE
Code in Jupyter notebooks still uses legacy IDAES API

### ISSUE THREAD

**Issue by lbianchi-lbl** [watertap-org/watertap#843]
This will need to be fixed for the notebooks to be runnable with version of IDAES after 2.0.0a3.

The fixes should consist mostly of:

- [ ] Use of `default={...}` init kwarg: `MyBlock(default={"foo": "bar"}` -> `MyBlock(foo="bar")`
- [ ] For the same underlying reason, `MyBlock(default=my_existing_dict)` -> `MyBlock(**my_existing_dict)`
- [ ] Another variant: `my_func(arg, default={})` -> `my_func(arg)`

**Comment by lbianchi-lbl** [comment]
@TimBartholomew the hastily-put-together PR #851 seems to be working, so once you have your PR up with the fixes it should be possible to combine the two so that we can ensure that the notebooks are working properly.

**Comment by ksbeattie** [comment]
Addressed by #859
