### ISSUE TITLE
Refine scaling utility

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#942]
I think that the `transform_property_constraints` utility would benefit from a doc string explaining what it is used for (despite it seeming obvious to us) and also, I see an issue with hard-coding a check for `"eq_" + var_str`. Does IDAES v2 enforce that property constraints be named that way? If not, then one could use this utility intending to scale constraints, but then they'd miss any constraints that don't follow this naming convention.

https://github.com/watertap-org/watertap/blob/31edc1a26a0eb94caacefbd5e04473ef4fab1bb3/watertap/core/util/scaling.py#L18-L30

**Comment by andrewlee94** [comment]
@adam-a-a IDAES has no requirements on constraint names. Also note however that IDAES intends to deprecate the existing scaling tools this year, and replace them with direct use of the Pyomo Scaling Transformation with some helper functions for automatically scaling models.

**Comment by adam-a-a** [comment]
Thanks, @andrewlee94. I doubted such requirements were introduced, but I figured I'd ask first. @MarcusHolly I tagged you as the assignee since I thought you were the one that originally implemented this utility.

**Comment by MarcusHolly** [comment]
@adam-a-a The change that you're asking for here is not very intuitive for me. I believe the second input for the `hasattr()` has to be a string, and, since the constraint name isn't being defined in the metadata, I'm not sure of how to get the constraint name without hard-coding it. 

Also just to be clear, the hard-coded portion was not a change that I made. That is how the transformations were being done in each of the property models beforehand; I just compiled them all into a utility function. There are actually still a few places in the property model files where `getattr(self, "eq_" + v_str)` is being used, so if there is a way to get around hard-coding, I should probably make the changes in these places as well.

**Comment by andrewlee94** [comment]
There is no way (currently at least) to link a specific variable to a constraint - that is purely up to the developer/end user and whatever convention they choose to use. Thus, the end user either needs to pick a specific convention (such as `"eq_+var_name"`) or hard coding the names. Also note that there is often not a simple 1-is-to-1 relationship between variable and constraint scaling.

**Comment by adam-a-a** [comment]
I think the reason this jumped out at me was because it was in a separate utility, which typically should be general enough to work across the board. I am recalling now that these hard-coded names were expected in, e.g., NaCl, seawater property models, so within those, we applied his hard-coded logic because we knew all constraints were named that way. Other property models probably followed suit. However, the following questions come to mind when we stick this into a general utility:

1) What happens when a user applies this to a newly developed property model and does not abide by this naming convention?

2) How would users know whether their property constraints were actually scaled or not?

**Comment by andrewlee94** [comment]
Ultimately, that is why scaling generally needs to be done on a unit-specific basis (at least as long as you expect users to build their own models).

That said, IDAES does now have a (prototype) generic tool for getting the  expected magnitudes of the terms in a constraint based on the variables that appear in it (see alter part of https://idaes-pse.readthedocs.io/en/latest/reference_guides/scaling.html).

**Comment by MarcusHolly** [comment]
> I think the reason this jumped out at me was because it was in a separate utility, which typically should be general enough to work across the board. I am recalling now that these hard-coded names were expected in, e.g., NaCl, seawater property models, so within those, we applied his hard-coded logic because we knew all constraints were named that way. Other property models probably followed suit. However, the following questions come to mind when we stick this into a general utility:
> 
> 1. What happens when a user applies this to a newly developed property model and does not abide by this naming convention?
> 2. How would users know whether their property constraints were actually scaled or not?

@adam-a-a 
1.) If a user is adept enough to develop their own property model, I think it's likely that they'll either know to adopt our naming conventions (either by looking at the utility function or other property models) or they could just scale the constraint without using the utility function. To make this a bit easier for less-experienced users, we could add How-To documentation for setting up property packages. Although this would probably end up being a pretty lengthy How-To. 

2.) Using the unscaled constraint generator? Not sure what kind of documentation exists on this either, but it could be mentioned in the aforementioned How-To.

EDIT: Removing this utility function and just adding it back into the individual property models does not necessarily address these concerns either though, right? Users could still fail to abide by the naming convention and not be sure whether their constraints were actually being scaled or not.

**Comment by adam-a-a** [comment]
Or we could display a logger warning after adding an `else` to the conditional `if hasattr(self, "eq_" + var_str): `.  

It could also be interesting to apply some of IDAES' new scaling functions that @andrewlee94 mentioned and potentially wrap those in our own utilities as we see fit, but that would probably be a separate effort, if we had any ideas there in the first place.

As for how-tos, IDAES does have some detailed docs on creating custom property models, so I am not sure about that route. However, we probably lack documentation on all of our utilities, so maybe part of the solution is to eventually add documentation for all of our utilities (technical references). 

In response to your edit, that's a good point, which made me recall that unscaled constraints would be caught by the corresponding test for checking that. However, treating the utility as an independent entity and not assuming any follow-up testing to check for unscaled constraints, we should do _something_ here to address it. Maybe by adding that `else` that I mentioned above. Curious to hear @bknueven's take as well.

**Comment by MarcusHolly** [comment]
One potential problem I see with just adding an `else` followed by a logger warning is that it might pick up variables in the metadata that have a method, but don't have a constraint. Specifically, I'm looking at `enth_flow`. I think this would cause the logger warning to display even though `enth_flow` doesn't have a constraint. I'm not sure if there are any other variables like this.

**Comment by bknueven** [comment]
We can find if something is an object reference by checking `var_str != var.name`.
