### ISSUE TITLE
Unkown error in docs/readthedocs.org:watertap

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#961]
### Description

docs/readthedocs.org:watertap unexpectedly failing in [https://readthedocs.org/projects/watertap/builds/19777707/](https://readthedocs.org/projects/watertap/builds/19777707/)

**Comment by lbianchi-lbl** [comment]
It looks like this hasn't showed up again (yet?). Let's leave this open for a while in case the error occurs again.

**Comment by hunterbarber** [comment]
@lbianchi-lbl Maybe time to clean this up and archive? Haven't seen it come up again.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Maybe time to clean this up and archive? Haven't seen it come up again.

Thanks for the suggestion, and, I agree.
