### ISSUE TITLE
InitializationError is NOT raised when expected

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#965]
### Description

For some reason, `InitializationError` doesn't raise when the NaCl stateblock fails to initialize. This bug was noticed while troubleshooting the OARO multi-stage PR (#897). To replicate, checkout PR #964 .

https://github.com/luohezhiming/watertap/pull/1/files
![image](https://user-images.githubusercontent.com/22691844/225435240-4f67a77b-6e94-4a77-b01a-8193f757d0af.png)

### Expected Behavior

We expect `InitializationError` to raise and for some odd reason, it does not. Yet, it appears that after the InitializationError line, the initialization routine does end for RO. 

### Steps to Reproduce

Checkout the branch oaro_multi from PR #964 and go to the `initialize` routine for the NaCl property package. Go to the end of the routine and try including the InitializationError. It won't raise, but an alternative exception will if you try one.

### Environment

- OS:
- Python:
- WaterTAP:

**Comment by adam-a-a** [comment]
@bknueven @andrewlee94 could use your help with this. Maybe this is just end-of-the-day burnout, but hitting a wall

**Comment by andrewlee94** [comment]
First of all, what is happening in this case? I see a lot of things in there that look like you are trying to debug the issue so I want to be sure I know what is happening.

Is the issue that the `if logic:` branch is not triggering as expected? I see that you have swapped the `InitializationError` for a `PropertyPackageError` and I want o make sure that you are not trying to say that the `PropertyPackageError` gets raised but not the `InitializationError`.

If that is the case, then you need to go look at `logic` first - is it taking the correct value?

**Comment by adam-a-a** [comment]
You're right- I should've cleaned things up to make it more clear. We looked at `logic` and it is `True` as expected. So we verified that we make it into that conditional and should trigger the `InitializationError`, but it just doesn't raise. Commenting out `InitializationError` and introducing any other `Exception`, that newly introduced `Exception` will be raised. So yes- "the PropertyPackageError gets raised but not the InitializationError."

**Comment by andrewlee94** [comment]
Are you sure that it is not getting raise, and not that it is getting handled by a try/except at a higher level? E.g. put the `PropertyPackageError` after the `InitializationError` and see it the `PropertyPackageError` gets raised. If it doesn't (which I suspect is hte case), then the `InitializationError` is being raise but caught by a `try/except`.

**Comment by adam-a-a** [comment]
You're right- `PropertyPackageError` didn't raise in that case. The odd thing is-- if `InitializationError` is being caught by a try/except, then if I take `InitializationError` out of that conditional and place it right before the `if logic:` conditional, it shouldn't raise. However, when I try that, `InitializationError` _does_ raise as expected.

**Comment by andrewlee94** [comment]
Then you have something very strange going on - you need to use the Python debugger to trace the steps as they happen.

**Comment by adam-a-a** [comment]
I found the issue. Looking at the inclusion of `InitializationMixin` in the unit model, it employs try/except for `InitializationError`. TBH- `InitializationMixin` was introduced while I was away, and I never grasped what it's true purpose was. @bknueven do you have any thoughts on this?

**Comment by adam-a-a** [comment]
Oh-so when I remove `InitializationMixin` from the unit model, `InitializationError` does get raised now from the NaCl prop package.

**Comment by bknueven** [comment]
We introduced the `InitializationMixin` because without it, certain stateblocks might not be released if the initialization fails. You can see the PR that brought it in here.

Probably the fix for this is to be a bit more careful in the mix-in's `initialize` method.

**Comment by bknueven** [comment]
It's also possible that the `InitializationMixin` is no longer needed with the latest release of IDAES.

**Comment by andrewlee94** [comment]
@bknueven Nothing changed in IDAES That would remove the need for the MixIn. There is a new initialization API, but it is completely different and would take some effort to move to.
