### ISSUE TITLE
Remove more unused imports

### ISSUE THREAD

**Issue by wigging** [watertap-org/watertap#994]
### Description

Using `flake8 --statistics --select=F401 --exclude=__init__.py .` gives 223 warnings about unused imports in watertap. I'll go through the package and remove these unused imports.

### Expected Behavior

Expect Python files to only import what is needed for the code in that file.

### Steps to Reproduce

Use the flake8 tool from within the watertap directory:

```
cd watertap
flake8 --statistics --select=F401 --exclude=__init__.py .
```

### Environment

- OS: macOS 12.6.3
- Python: 3.10
- WaterTAP: latest version

**Comment by lbianchi-lbl** [comment]
For reference, this is the corresponding Pylint message that should be enabled in the PR addressing this so that this check is enforced by our CI: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-import.html
